### ISSUE TITLE
Inbound proxy metrics for controller component include prometheus scrape request

### ISSUE THREAD

**Issue by klingerf** [runconduit/conduit#1012]
Our prometheus scrape config for conduit is configured to scrape metrics from all of our controller components. It looks like those scrape requests are being routed through the conduit proxy running in each controller pod and tracked as part of our inbound request stats. These requests are then reflected in our controller stats.

For instance, in my setup I'm not sending any traffic to grafana, but the stat output gives me:

```
$ conduit -n conduit stat deploy/grafana
NAME      MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   SECURED
grafana      1/1   100.00%   0.1rps          15ms          20ms          20ms        0%
```

The 0.1rps reported is from the scrape request running every 10 seconds.

I see similar metrics in the web pod's proxy:

```
response_total{authority="172.17.0.6:9994",direction="inbound",classification="success",status_code="200"} 24
```

And the controller pod's proxy:

```
response_total{authority="172.17.0.8:9995",direction="inbound",classification="success",status_code="200"} 36
response_total{authority="172.17.0.8:9996",direction="inbound",classification="success",status_code="200"} 36
response_total{authority="172.17.0.8:9998",direction="inbound",classification="success",status_code="200"} 36
response_total{authority="172.17.0.8:9999",direction="inbound",classification="success",status_code="200"} 35
```

It's possible that this is all behaving correctly: maybe the stats in the conduit namespace should reflect scrape requests from the prometheus component to other component in the namespace. But it was a bit unexpected (for me), so I at least wanted to document it in an issue. I'd be totally fine with closing this as "working as expected".

**Comment by olix0r** [comment]
I don't think there's anything _wrong_ with this behavior, though we could decide that this shouldn't happen.  I think it's fine and good, though, for tap requests, for instance, to show the prometheus requests hitting containers in a pod.

As a point of reference, this will almost certainly be the behavior for non-Conduit prometheus installs -- as prometheus hits application containers to collect metrics, these requests will traverse the proxy and be recorded in the UI, etc.

**Comment by siggy** [comment]
I'm inclined to mark this "working as expected". In the spirit of #984, I think we should dogfood conduit as much as possible.

**Comment by klingerf** [comment]
Awesome, I think we're all in agreement. Closing.
