### ISSUE TITLE
Ensure the `tls` label is being picked up by cli/web/tap

### ISSUE THREAD

**Issue by rmars** [runconduit/conduit#1017]
#996, #983, and #1021 add `Secured` columns to the `conduit tap` output, `conduit stat` output, web UI, and Grafana. They use a label called `tls` from the proxy on inbound and outbound traffic, but the proxy doesn't yet add these labels. After the proxy supplies these labels, we should double check that everything is propagated correctly:

- run `conduit tap` and ensure you can see `secured=yes` in fully meshed requests
- run `conduit stat` and ensure the `Secured` column displays non-zero values (i.e. 100% for fully meshed requests)
- open the web UI, go to a namespace (or resource) page, and ensure the last column displays non-zero values
- open Grafana, view the Top-line Request Volume graph

Relates to #388

**Comment by klingerf** [comment]
As part of this issue we should also unhide the `--enable-tls` install flag, which is [currently hidden](https://github.com/runconduit/conduit/blob/master/cli/cmd/install.go#L82).
