### ISSUE TITLE
Dashboard error - Error getting data from server: Failed to fetch.

### ISSUE THREAD

**Issue by markharrisonuk** [runconduit/conduit#1045]
I get the dashboard displayed with the Service Mesh Overview - all looks good, showing the Control Plane and Data Plane. I see my deployments, pods etc.

When I navigate to Dashboards | Replication  Controllers | Pods, I get an error "Error getting data from server: Failed to fetch."

**Comment by markharrisonuk** [comment]
It was my Ad Blocker … disabling that sorted things.

**Comment by wmorgan** [comment]
Yeah, known problem. It's a bit silly. See #970. Glad you got it working.
