### ISSUE TITLE
Extract and test protobuf-over-http code

### ISSUE THREAD

**Issue by klingerf** [runconduit/conduit#106]
As part of #103, our client/server implementations for the public API were refactored, but they're still pretty convoluted. Specifically, the protobuf-over-http setup is brittle and not thoroughly tested. We should move that code to a separate package and add additional tests.

**Comment by pcalcado** [comment]
I'm not sure if possible and/or should be part of the scope here but I'd really ❤️  to see test cases that actually run a client against a server on the same process and localhost and exercises some endpoints to end-to-end test the whole implementation.

**Comment by briansmith** [comment]
I think what we're doing is duplicating stuff that's already a reusable part of client-go, so an alternative to this would be to reformulate our APIs to be implemented in terms of client-go's reusable library. If it can be made to work like that then I think that would be better than maintaining our own similar-but-different logic. I looked into this before and it seemed like it should be possible, but I admit I didn't quite understand the client-go code well enough to write a PR for it.

**Comment by klingerf** [comment]
Am updating our client-go dependency in #122.
