### ISSUE TITLE
proxy: Test filesystem watching code with a Kubernetes ConfigMap

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#1061]
We should ensure the filesystem watching code added in 7220fb53670e2bfe2d9424d97edcd40d4d839a83 is able to detect changes in a Kubernetes ConfigMap as a volume mount. @klingerf informs me that in the past, we ran into some issues where changes to ConfigMaps don't correctly change the last modified timestamp. This may have been fixed in Kubernetes, so we should do some testing to determine if this works.

**Comment by briansmith** [comment]
> changes to ConfigMaps don't correctly change the last modified timestamp.

We don't actually care about the timestamp. What really matters is whether inotify gives us an indication. We should just assume any/all the files changed and not look at the timestamps when we get a notification.

**Comment by hawkw** [comment]
@briansmith 
> We don't actually care about the timestamp. What really matters is whether inotify gives us an indication.

That's correct, the `inotify`-based implementation that I'm currently working on won't use the timestamps. However, the _polling-based_ code that was merged to master in 7220fb5 _does_ rely on timestamps to detect changes.

Until the `inotify`-based code is merged to master, we should ensure that the current master works correctly with configmaps. We should also ensure that `inotify` correctly detects changes to configmap volume mounts.

**Comment by briansmith** [comment]
> However, the polling-based code that was merged to master in 7220fb5 does rely on timestamps to detect changes.

Sure. I guess we should just change it to read in the file contents and compare them to the previous contents, instead of comparing timestamps; i.e. act like we got an inotify notification at every interval.

We can store the `ring::digest::Digest` using SHA-384 of each file, and compare the digests to determine equality, so we don't have to keep the entire file contents in memory separately from the copy that is eventually made.

**Comment by briansmith** [comment]
I see the issue here: https://github.com/kubernetes/kubernetes/issues/24215

It seems like inotify might not work like we expect in this symlink-to-symlink kind of configuration either. :(

**Comment by hawkw** [comment]
I've manually verified that (at least on Kubernetes v1.9.6 running in Docker for Desktop 18.05.0-ce-mac66), @klingerf is correct, and the current approach does _not_ detect ConfigMap changes. 

I'm planning on following your suggestion that
> We can store the `ring::digest::Digest` using SHA-384 of each file, and compare the digests to determine equality, so we don't have to keep the entire file contents in memory separately from the copy that is eventually made.

In the longer term, since `inotify` may also not detect these changes, we _might_ want to look into watching the Kubernetes API instead of mounting the TLS configuration as a volume mount. However, that's its' own can of worms, and I'm not sure if it would be better...

**Comment by hawkw** [comment]
If my understanding of the issue @briansmith linked is correct, we may still be able to use `inotify` if we watch the directory _containing_ the files. If the files are in different directories, we can still get the parent dir from the path and watch all such directories. 

This could lead to false positives if those directories also contain files we _don't_ care about watching, but I think occasionally reloading the files when we didn't have to is better than having to constantly reload and hash them.

Will do some additional research.

**Comment by briansmith** [comment]
@hawkw I don't think #1077 closes right, right? Because we don't have the tests merged yet?

**Comment by hawkw** [comment]
Yeah, I suppose you're right; I was treating this issue as tracking the _problems_ with fs watches on k8s and not on actually adding the tests, although that is the name of the issue. I probably should have opened two separate tickets...
