### ISSUE TITLE
proxy: Fs polling code doesn't detect changes within the same second (on macOS)

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#1090]
I've been working on writing tests for the filesystem watching code added in #1056 and #1077, and have found a bug:

When multiple watched files are created or modified within 1 second of each other, the polling-based watch stream only detects one change, at least on macOS. This is because the last modified timestamps in the filesystem metadata are reported with 1-second resolution on macOS.

According to the 2008 POSIX standard, the `stat.st_mtim` field is _supposed_ to be reported as a `timespec` with nanosecond resolution, but it appears that macOS does not set the nanoseconds field. I suspect other Unices implement this correctly.

**Comment by hawkw** [comment]
AFAICT, the only way to fix this across all platforms is to change the polling code to compare file hashes --- if anyone can think of a better approach, I'd be eager to hear suggestions.

**Comment by briansmith** [comment]
> AFAICT, the only way to fix this across all platforms is to change the polling code to compare file hashes --- if anyone can think of a better approach, I'd be eager to hear suggestions.

I was worried about this because I know Windows is the same way. The target platform is Linux though. However, I agree in general that comparing timestamps should be avoided.

**Comment by briansmith** [comment]
> @olix0r suggested that we just modify the tests to work around this by sleeping for a couple seconds between modifications.

I would rather not have the tests run for multiple seconds per iteration. Calculating the hash is just `use ring::digest; let digest = digest::digest(&digest::SHA384, file_contents);` and I think it's straightforward to store the last digest next to each `PathBuf` holding the filename, especially after we introduced the fold-based structure anyway.

**Comment by olix0r** [comment]
@briansmith that's fair. i was worried the hashing solution was going to be more complex.

**Comment by hawkw** [comment]
@briansmith Okay, I'll just change it to use hashing then. Do you think calculating the SHA384 is going to take long enough that we ought to change the poll interval?

**Comment by briansmith** [comment]
> Do you think calculating the SHA384 is going to take long enough that we ought to change the poll interval?

No, it will take almost no time. (SHA-384 is faster than SHA-256 on 64-bit platforms, usually, BTW.)
