### ISSUE TITLE
`--registry` does not override the proxy images

### ISSUE THREAD

**Issue by grampelberg** [runconduit/conduit#1100]
When doing `conduit install --registry foobar`, I would expect the proxy images to be overridden as well as the control plane. Instead, the proxy and proxy-init images stay the same.

Should `--registry` override the registry for prometheus as well? It doesn't look like there's a way to modify the prometheus image right now.

**Comment by klingerf** [comment]
I agree that the `--registry` flag should also override the proxy image's registry, and in that case we'd need to support a `--registry` flag for the `conduit inject` command -- right now it's only supported for `conduit install`.

But I'm also curious to know if we have a concrete use case for the `--registry` flag? I'd be inclined to just remove it unless there's some compelling reason to keep it around.

**Comment by grampelberg** [comment]
It'd be nice to use when running conduit in a totally disconnected k8s cluster. I'll admit that's a minor use case though. It is possible to get (mostly) there with the flags that exist today, so I'd argue this is a minor bug at best.

**Comment by klingerf** [comment]
Related to this issue, the inject command also supports the following two flags:

```
      --init-image string               Conduit init container image name (default "gcr.io/runconduit/proxy-init")
      --proxy-image string              Conduit proxy container image name (default "gcr.io/runconduit/proxy")
```

If we update inject to support the `--registry` flag, should we remove those two flags? Or should we have some sort of fallback logic in place, where setting `--registry` overrides the registry that's set as part of either of those two flags?

```
