### ISSUE TITLE
Proxy doesn't load TLS configuration files if they exist before proxy is started

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#1133]
Before and after #1119, the proxy doesn't load its TLS configuration, and so starts in a no-TLS configuration, when the configuration files already exist and are already valid. I have to `touch` one of the configuration files, which causes the fs_watch code to load the configuration.

/cc @hawkw

**Comment by hawkw** [comment]
Ah, yeah, we should probably attempt to load the configuration files once before we start the watch, that should be fairly easy to fix. I'll see about adding a test for this as well.
