### ISSUE TITLE
Display stats by authority in the web and CLI

### ISSUE THREAD

**Issue by rmars** [runconduit/conduit#1147]
For services external to the mesh, we collect stats by authority in prometheus, but we don't display them anywhere. Add these to the web and CLI so that we have a more comprehensive view of traffic.

**Comment by olix0r** [comment]
Some thoughts:

* As a first implementation, I wouldn't try to distinguish between internal and external names. Let's just make this a way to query/view traffic by the authority (so, for instance, authority/foo.bar.svc.cluster.local and svc/foo in the bar namespace will have identical stats).

* We shouldn't worry about normalization yet.  This means that `foo` and `foo.bar.svc.cluster.local` and `foo:80` may all be different values of authority that represent the same logical endpoint. The proxy should (eventually) handle this normalization.

**Comment by rmars** [comment]
Here are some example `conduit stat` commands demonstrating how I think we might use `authority`:

```
$ conduit stat authority web-svc.emojivoto:80 -n emojivoto
NAME                    MESHED   SUCCESS      RPS      LATENCY_P50   LATENCY_P95   LATENCY_P99   SECURED
web-svc.emojivoto:80    2/2      100.00%      1.0rps           5ms          10ms          10ms        0%

$ conduit stat deploy/web -n emojivoto --to-authority voting-svc.emojivoto:8080
NAME   MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   SECURED
web       2/2    86.07%   2.0rps           5ms          10ms          10ms        0%

$ conduit stat authority -n emojivoto --from deploy/web
NAME                         MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   SECURED
voting-svc.emojivoto:8080       2/2   100.00%   2.1rps           5ms          10ms          10ms        0%
emoji-svc.emojivoto:8080        2/2   100.00%   2.1rps           5ms          10ms          10ms        0%
```

**Comment by rmars** [comment]
API proto changes needed to add Authority to the stat request and to the --to filters:

```
message Authority {
  // The authority that receives traffic
  // Can only receive traffic, not send it.
  string name = 1;
}

message StatSummaryRequest {
  oneof selector {
    ResourceSelection resource = 1;
    Authority authority = 7;
  }

  string time_window = 2;

  oneof outbound {
    Empty none = 3;
    Resource to_resource   = 4;
    Resource from_resource = 5;
    Authority to_authority = 6;
  }
}
```

**Comment by olix0r** [comment]
@rmars What do you think about treating "authority" as a special, virtual resource type, rather than handle it as a separate API entity?  Are there advantages to modelling it separately?

**Comment by rmars** [comment]
I was just thinking about that myself! The initial concern I had was that we designed Resource to be specific to a k8s resource, and I was worried about shoving a non-k8s-resource into that same model, since you can have authorities not in k8s.

An authority could just be a resource of type "authority" though.

**Comment by olix0r** [comment]
Unless someone (hi @grampelberg) tells me this is a terrible idea, i'm partial to carving out some additional reserved resource types.

**Comment by rmars** [comment]
This would be my proposal for the `Resource` documentation if so:

```
message Resource {
  // The namespace the resource is in.
  //
  // If empty, indicates all namespaces should be considered.
  string namespace = 1;

  // The type of resource.
  // This can be
  // - a Kubernetes resource, e.g. pod, deployment, service, ...
  // - a non-Kubernetes resource such as an Authority
  //
  // If `all` refers, to all Kubernetes resource types only.
  string type = 2;

  // An optional resource name.
  string name = 3;
}
```

**Comment by olix0r** [comment]
@rmars i like it!

I might phrase it like this:

```protobuf

  // The type of resource.
  //
  // This can be:
  // - "all" -- includes ALL resource types
  // - "authority" -- a special resource type derived from request `:authority` values
  // - Otherwise, the resource type may be any Kubernetes resource (e.g. "namespace", "deployment").
  string type = 2;
```

It would be my preference to include authorities with _all_

**Comment by grampelberg** [comment]
```
conduit stat --to authority/www.google.com:80
```

That gets me excited.
