### ISSUE TITLE
proxy-deps docker image tag hash should depend on Dockerfile

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#115]
https://github.com/runconduit/conduit/pull/105 modified `proxy/Dockerfile-deps` to depend on `rust:1.23.0` rather than `rust:1.21.0`, but since the tag on `gcr.io/runconduit/proxy-deps` only depends on `Cargo.lock`, the image never updated.

We should fix our build such that modifying `proxy/Dockerfile-deps` or `Cargo.lock` causes the image tag to change.

**Comment by hawkw** [comment]
c30fb12aadbaf99feefd8f31756f66182cf82900 adds a comment in `proxy/Dockerfile-deps` warning about this issue and advising anyone changing that file to touch the lockfile as well. This isn't a _fix_, exactly, but should help us to avoid issues like this in the future.
