### ISSUE TITLE
Proxy Connection no longer uses vectored writes

### ISSUE THREAD

**Issue by seanmonstar** [runconduit/conduit#1162]
Since `Connection` uses a boxed trait object (trait includes `AsyncWrite`), the calls to `Connection::write_buf` make use of the default `AsyncWrite::write_buf` method, which doesn't use vectored writes.

To fix this, I believe we'd need to stop holding a `Box<Io>`, and instead hold an enum of either `TcpStream` or `TlsStream`.

**Comment by briansmith** [comment]
Why can't we extend the `Io` trait with a vectorized write mechanism? How does the vectorized write mechanism work?

**Comment by hawkw** [comment]
@briansmith I believe the vectored write implementation for `TcpStream` @seanmonstar is referring to is [here](https://tokio-rs.github.io/tokio/src/tokio_tcp/stream.rs.html#569).

**Comment by seanmonstar** [comment]
It looks like this:

```rust
trait AsyncWrite {
    fn write_buf<B: Buf>(&mut self, buf: &mut B) -> Poll<usize, io::Error> where Self: Sized {
        // default is to just self.write(buf.first_slice())
    }
}

// for TcpStream
impl AsyncWrite for TcpStream {
    fn write_buf<B: Buf>(&mut self, buf: &mut B) -> Poll<usize, io::Error> {
        // simplified
        let mut iovecs = [IO_VEC_INIT; 64];
        let cnt = buf.bytes_vec(&mut iovecs);
        self.inner.writev(&mut iovecs[..cnt])
    }
}
```

The problem is that `write_buf` requires `Self: Sized`, which `Box<Io>` isn't, so it uses the default one instead. I don't know what all the type trickery would be needed, maybe adding some sort of `write_buf_erased(&mut self, buf: &mut Buf)` to the `Io` trait, and then implementing that for `TcpStream`?

**Comment by hawkw** [comment]
I suspect just going back to using an `enum` is probably the easier solution, especially since it  seems we _do_ often care about whether or not the connection is TLS...

**Comment by seanmonstar** [comment]
So, yes, I just got an erased version working in a [playpen](https://play.rust-lang.org/?gist=e28e09e25cb0e62fbbf701480bb6b775&version=stable&mode=debug). I think we can get it working with this change:

```rust
trait Io: AddrInfo + AsyncRead + AsyncWrite + Etc {
    fn write_buf_erased(&mut self, buf: &mut Buf) -> Poll<usize, io::Error>;
}

impl Io for TcpStream {
    fn write_buf_erased(&mut self, mut buf: &mut Buf) -> Poll<usize, io::Error> {
        self.write_buf(&mut buf)
    }
}
```

**Comment by briansmith** [comment]
> especially since it seems we do often care about whether or not the connection is TLS...

Do we? I think we care about the distinction up until the `Connection` is created, and then we never branch on it again.

**Comment by briansmith** [comment]
I'm not opposed to the enum solution and I dislike `Box` in general but I also hate duplicating `match { case 1, case 2, case 3 }` over and over again (3 cases would be required, 1 for no TLS, one for TLS clients, and one for TLS servers), so @seanmonstar's erased variation looks better to me.

Can/should we put a `where Self: Sized` constraint on the `impl Io for TcpStream` to statically guarantee that its specialized `write_buf` is used?

**Comment by seanmonstar** [comment]
@briansmith how does that work?
