### ISSUE TITLE
Stop vendoring proxy dependencies

### ISSUE THREAD

**Issue by carllerche** [runconduit/conduit#119]
Currently, the proxy has many of its dependencies vendored in this git repository. These libraries are now being developed in their own git repositories. We should update the proxy to track these repositories in a controlled fashion.

* Tower: https://github.com/tower-rs/tower
* Tower H2: https://github.com/tower-rs/tower-h2
* Tower gRPC: https://github.com/tower-rs/tower-grpc
* Codegen: https://github.com/carllerche/codegen

Additionally, the proxy should probably track Tokio & futures development:

* Tokio: http://github.com/tokio-rs/tokio
* Futures: https://github.com/alexcrichton/futures-rs/tree/tokio-reform

We want to make sure that breaking changes in these repositories do not break our build, so we should pin to specific git refs.

**Comment by xiaods** [comment]
yes, in golang convention, it should be put int a separate folder to store the state of art codebase.

**Comment by olix0r** [comment]
@xiaods this is unrelated to our Go dependencies, which are already vendored with godep. This project originally included several additional libraries which have since been split into new repos. This issue simply tracks adopting the new repos as a source of truth for these dependencies.

**Comment by hawkw** [comment]
I've made some progress on this. Stumbled across some `tower-grpc` issues in the process (tower-rs/tower-grpc#31, tower-rs/tower-grpc#33), but I'm now starting to get to a point where `tower-grpc-build` will once again output compile-y code from Conduit's protos. Still working on changing the non-generated code in the proxy to work with `tower-grpc` APIs that have changed.

**Comment by hawkw** [comment]
Current work in progress state: 8213b92b7190dd697530cc41a70761a08bd5e62d

**Comment by hawkw** [comment]
I believe this was closed by #225.
