### ISSUE TITLE
proxy: Add additional smaller buckets for response_latency_ms

### ISSUE THREAD

**Issue by klingerf** [runconduit/conduit#1208]
It looks like the smallest bucket exported by the proxy for response_latency_ms is 10ms. For example:

```
# TYPE response_latency_ms histogram
response_latency_ms_bucket{authority="t1-svc:9090",direction="inbound",classification="success",status_code="200",grpc_status_code="0",le="10"} 1260
response_latency_ms_bucket{authority="t1-svc:9090",direction="inbound",classification="success",status_code="200",grpc_status_code="0",le="20"} 1274
response_latency_ms_bucket{authority="t1-svc:9090",direction="inbound",classification="success",status_code="200",grpc_status_code="0",le="30"} 1276
...
```

This leads to extrapolation when computing percentile latencies for relatively fast services:

```
$ conduit stat -n conduit-tap-test deploy
NAME      MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   SECURED
gateway      1/1     0.00%   1.0rps           6ms          15ms          19ms        0%
t1           1/1   100.00%   1.0rps           5ms          10ms          10ms        0%
t2           1/1     0.00%   1.0rps           5ms          10ms          10ms        0%
t3           1/1   100.00%   1.0rps           5ms          10ms          10ms        0%
```

The `t1`, `t2`, and `t3` deployments all have identical `P50`, `P95`, and `P99` latencies, since the actual response latency for all three deployments is <10ms at p99.

It would be better if we had smaller buckets to capture sub-10ms latencies. I think at one point our smallest bucket was 0.1ms. But from my perspective 1,2,5,10,20,... would probably suffice.

**Comment by olix0r** [comment]
Yeah, I agree that we should restore at least `[1,2,3,4,5,...` ms buckets at the start.
