### ISSUE TITLE
Is there any plans to add "circuit-breaking" support or some others,just like Linkerd?

### ISSUE THREAD

**Issue by Aavon** [runconduit/conduit#1255]
We are determine to use Linkerd or Conduit,even istio.We think if conduit have(or to be) the advance features,conduit will be the best choice.But we are not sure you have the plan and we can push it together.

**Comment by olix0r** [comment]
Hi @Aavon! Conduit's load balancer already has some circuit-breaker-like features. Can you describe in more detail the failure scenarios that you are looking to address?

**Comment by Aavon** [comment]
Ooh,that's my fault,I did not read the documentation carefully.They are written on [roadmap](https://conduit.io/roadmap/) is very clear
There are two main problems.

1.Is Conduit Kubernetes version dependent，we are using 1.8+,1.9+
2.How about the router-rule features?Are they commin with version 0.5?

(personally,how about push the docker images to docker.io...)

Hope for your reply!
