### ISSUE TITLE
change css variables for color to be more descriptive

### ISSUE THREAD

**Issue by franziskagoltz** [runconduit/conduit#135]
currently some of the variables in css representing a color are named: 
`  --latency-p99; 
  --latency-p95; 
  --latency-p50`

it would be great to change the naming to be descriptive of the variables representing colors, as is done with other variable names. 
![screen shot 2018-01-10 at 3 50 15 pm](https://user-images.githubusercontent.com/12401925/34801881-b16590e0-f61f-11e7-8727-5a202620cefb.png)

**Comment by rmars** [comment]
Suggestion: we use something like http://chir.ag/projects/name-that-color/#56CCF2 to help us get a human readable, descriptive color name for each color.

**Comment by rmars** [comment]
(name that color still won't produce a unique name for every hex color, but it does help, and probably gets us most of the way)

**Comment by rmars** [comment]
Fixed by https://github.com/runconduit/conduit/pull/147
