### ISSUE TITLE
reassess DOCKER_FORCE_BUILD

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#141]
motivated by: https://github.com/runconduit/conduit/pull/137#discussion_r161080303

`DOCKER_FORCE_BUILD` may not be doing what we think it's doing:
https://github.com/runconduit/conduit/blob/master/bin/_docker.sh#L90

consider fixing the build scripts to always rebuild if the `latest` tag is set, or even remove this flag entirely and rely on docker build caching.

**Comment by olix0r** [comment]
Can you explain in more detail what you think it's doing versus what it's actually doing?

**Comment by siggy** [comment]
This comment at the top of `docker_maybe_build`:
`If the tag is 'latest', an image will always be built.`

...but my reading of that function, where `DOCKER_FORCE_BUILD` is not set, is that it will always rely on already built images:
```
    if [ -z "${DOCKER_FORCE_BUILD:-}" ]; then
        docker pull "${repo}:${tag}" >/dev/null 2>&1 || true

        for t in $(docker_tags "${repo}:${tag}") ; do
            if [ "$t" = "$tag" ]; then
                docker tag "${repo}:${tag}" "${repo}:latest" >/dev/null

                echo "${repo}:${tag}"
                return 0
            fi
        done
    fi
```

**Comment by olix0r** [comment]
Ahh yeah, the _latest_ behavior was changed without updating the comment, I believe.

Relying on only on docker caching would be nice, though I think that's going to be a bit tricky.

In the short-term, i'd suggest that we ensure the scripts are commented appropriately -- I'm happy to help with that.

If we're going to retool all of the build stuff, we need to be clear in scoping/motivating that work. I don't think it should be a priority unless the current tools are actively causing problems.

**Comment by klingerf** [comment]
Am not sure @siggy is suggesting retooling all of our build stuff, but it would be nice to fix the script with regard to the latest tag. I do think it always makes sense to rebuild the latest tag, instead of potentially pulling whatever's currently tagged as latest on gcr.io.
