### ISSUE TITLE
Consolidate version number in a single place

### ISSUE THREAD

**Issue by pcalcado** [runconduit/conduit#146]
Right now a checkout of the repository will have version information spread at least on the [`$TAG` env var used by the Docker build](https://github.com/runconduit/conduit/blob/e328db7e8740a4d01c99ba8c8bc05e236cf95d72/bin/_docker.sh#L82) and various places that use the constant in [`controller.Version`](https://github.com/runconduit/conduit/blob/e328db7e8740a4d01c99ba8c8bc05e236cf95d72/controller/version.go). This requires us to remember to change versions in both places.

Version information should live in a single place, hopefully in a plain text file.

**Comment by klingerf** [comment]
Just noting that the version number also lives in all of these places too:

```
$ find . -name Cargo.toml | xargs grep '^version'
./codegen/Cargo.toml:version = "0.1.1"
./futures-mpsc-lossy/Cargo.toml:version = "0.0.1"
./proxy/Cargo.toml:version = "0.1.1"
./tower-grpc/Cargo.toml:version = "0.1.1"
./tower-grpc-build/Cargo.toml:version = "0.1.1"
./tower-grpc-examples/Cargo.toml:version = "0.1.1"
./tower-h2/Cargo.toml:version = "0.1.1"
./tower-router/Cargo.toml:version = "0.1.1"
```
