### ISSUE TITLE
determine canonical way to test rust

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#149]
Follow up from https://github.com/runconduit/conduit/pull/137#discussion_r160865915.

The Travis script runs `cargo check && cargo test`, and testing is also documented this way in the nascent BUILD.md. Is this necessary? Is `cargo test` a superset of `cargo check`?

**Comment by hawkw** [comment]
My understanding is that `cargo test` will first attempt to build the project (and thus fail with any errors that fail `cargo check`) before it runs tests, so running both shouldn't be necessary. 

The Git blame indicates that the relevant lines in `.travis.yml` were written by @olix0r, so I suspect that if there's a reason for running both, he'd know what it is?

**Comment by briansmith** [comment]
> Is cargo test a superset of cargo check?

* `cargo check` checks (parses, performs name resolution, checks types, runs borrow checker) the non-test code.
* `cargo build` does what `cargo check` does plus codegen for non-test code.
* `cargo test` does what `cargo build` does, plus checking the test code + codegen for the test code + running the generated test code.
* `cargo check --test` does what `cargo test` does - all codegen - running the generated test code.

> I suspect that if there's a reason for running both, he'd know what it is?

I support removing the separate `cargo check` step. I think the idea was to make the build fail quicker if there was a problem with the code. However, I think we should to the state where we don't even submit things for CI unless we expect `cargo check` to pass, so I think it ends up just slowing things down now.

**Comment by olix0r** [comment]
@briansmith's post-hoc rationalization is spot-on :)  i'm fine with whatever here.
