### ISSUE TITLE
Destinations service doesn't discover services outside the local cluster

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#155]
If the DNS name sent in a query to the Destinations service has a suffix of "cluster.local" or whatever the current cluster domain name is, the Destination service should use the local k8s API server's Services API to discover the service. There are two cases:

* If the service is not an "external" service then the Destinations service should use the EndPoints API to watch the addresses for the service. This works now.

* If the service is an "external" service, then the Destination service should use DNS to discover the addresses for the service, as kube-proxy would. It should periodically poll DNS to get a similar effect toa watch on the EndPoints API for internal services. This doesn't work now.

If the DNS name sent in the query to the Destinations service doesn't end with "cluster.local" or the local cluster domain name, then the Destinations service should skip using the Services API and assume that it is an "external" service. This doesn't work now.

**Comment by briansmith** [comment]
FYI, I identified the most likely place where we need to kick off the DNS stuff in the Destinations service at https://github.com/runconduit/conduit/blob/5628d3c8f400ed4f3879dde7f4c1e0578432233b/controller/destination/server.go#L129. That's the point where we've ruled out the possibility that it is a local service.

**Comment by briansmith** [comment]
Basically the idea here is to replace that "// TODO: ..." comment with a service that polls DNS for the given name at regular intervals (no larger than the shortest TTL from previously-received A/AAAA records for that DNS name, and probably much shorter) and implements the controller side of the Destination service:
* When new (not currently in cache) A/AAAA records are received, send "add" notifications to the proxies.
* When A/AAAA records expire (based on their TTLs), send a "remove" notification to the proxies.

**Comment by seanmonstar** [comment]
Do we really want to build our own DNS polling service? Does Kubernetes not include something that consolidates it all?

Looking at DNS APIs in Go, I notice the main `net` package doesn't have a way to query records, only IP addresses. Google searches suggest https://github.com/miekg/dns to do record lookups...

**Comment by briansmith** [comment]
AFAICT, Kuberentes assumes that the clients themselves are going to do its own DNS polling. Basically the Destination service acts like a recursive resolver where the outbound queries are over DNS and the inbound queries are using the Conduit Destinations API, and so we have to implement something that bridges that gap.

**Comment by seanmonstar** [comment]
OK, here's my original plan:

1. Replace that `TODO` line with a `return resolvePublicDns(host, stream)`.
2. Use https://github.com/miekg/dns for DNS queries.
3. Start with an empty `map[string]IP` in `resolvePublicDns`.
4. Build a `dns.Msg` for A and AAAA records for provided host string.
5. Any IP not in map, push on map and on stream. Any IP in map but not in answer is removed and also notified on stream.
6. Keep an `interval` variable that is based on the smallest TTL from all the answers.
7. After interval expires, repeat from step 4.
8. All of this is joined on `<-stream.Context.Done()`.

Does this seem right? Is it gopherish? @siggy or @adleong?

 Also:

- What should happen if the dns queries see an error? Have some retries? Or just send the error back on the stream and close?
- This doesn't try to consolidate if multiple proxies all are asking about the same hostname. It'd probably be best to do so, but we also don't consolidate asking the Kubernetes API either. Perhaps a future optimization?

**Comment by briansmith** [comment]
> What should happen if the dns queries see an error? Have some retries? Or just send the error back on the stream and close?

See #335, where I ask the same question for the currently-implemented stuff.

> This doesn't try to consolidate if multiple proxies all are asking about the same hostname. It'd probably be best to do so, but we also don't consolidate asking the Kubernetes API either. Perhaps a future optimization?

I think this optimization is pretty essential at least for cluster-internal services. I filed #334 to track implementing it.

> What should happen if the dns queries see an error?

There are lots of exception cases. Two important ones to care about are:
* You don't get a response and time out. In that case, I would requery, and I would make the timeout short.
* You get a response that doesn't have any A or AAA records. You'll have to reschedule the query as though you got a response with a short TTL, because in a healthy system this probably means that the target services aren't quite ready yet but will be ready soon.

**Comment by seanmonstar** [comment]
The amount of work to query for records is quite a lot, compared to the default `net.LookupHost` call. The only thing gained from all of that is a list of TTLs. To reduce the scope of this, should we just use `net.LookupHost` and treat all records with a relatively short default TTL?

**Comment by briansmith** [comment]
1ms is probably not a reasonable interval for us to use as the default fixed TTL. However, there will be services that have a 1ms TTL and expect to have DNS polled that often. Thus, I think we will need to do things in a way that respects TTLs that are shorter than whatever short fixed TTL we start with.

So, if it doesn't seem like a huge amount of work to do it in terms of net.LookupHost and then do it in a TTL-sensitive manner then I think that that would be a reasonable progression.

**Comment by seanmonstar** [comment]
> However, there will be services that have a 1ms TTL and expect to have DNS polled that often.

Is this case common enough that it's worth us writing several hundreds of lines to manage a dns client manually (rotate nameservers, try TCP and UDP, poll `/etc/resolv.conf` for updates, handle DNSSEC, etc)?

Probably eventually, but as something that we hope to ship this week in 0.3?

> if it doesn't seem like a huge amount of work to do it in terms of net.LookupHost and then do it in a TTL-sensitive manner then I think that that would be a reasonable progression.

I don't quite get what this means. It's not a lot of work to set up a loop using just `net.LookupHost` on a specified interval (probably 10ish lines). However, it is **impossible** to get a TTL using the default `net` package, so we can't make it TTL-sensitive at all.

Unless you're saying do it first with just `net.LookupHost`, and then scope out all the work needed to run our own proper resolver for another milestone.

**Comment by briansmith** [comment]
> Is this case common enough that it's worth us writing several hundreds of lines to manage a dns client manually 

yes>

> (rotate nameservers, try TCP and UDP, poll /etc/resolv.conf for updates,

We can assume we're talking to the default Kubernetes internal DNS server (Kube DNS or CoreDNS) and that UDP is supported. We can assume a fixed /etc/resolv.conf, I think.

> handle DNSSEC, etc)?

We don't need to support DNSSEC.

**Comment by briansmith** [comment]
Also, @seanmonstar, please check out #62. Getting that resolved is important because if the resolution I propose in #62 isn't considered satisfactory, then the whole implementation strategy would need to change; in particular DNS would have to be implemented in the proxy instead of in the controller, at least some of the time.

**Comment by seanmonstar** [comment]
I hadn't seen #62, but I had read a bunch about Kube DNS, and was thinking that probably, the value of `SO_ORIGINAL_DST` would be the result of the pod having done DNS itself when trying to talk to the outside world...

**Comment by seanmonstar** [comment]
Would love some input from someone with more Go and/or controller experience, (sorry for ping bomb), @siggy @adleong...

Also, @ver on thoughts of requirements versus release milestone date...

**Comment by seanmonstar** [comment]
Oliver mentioned earlier today that [CoreDNS](https://coredns.io/) might be something that we could make use of, and it does have a way to talk to it with gRPC. However, even the gRPC route requires creating `dns.Msg`s, and sends one back, requiring a bit more work to get going. It'd also mean we would need to figure out running it as an extra service, like how we include Prometheus.

In #360, I have an initial attempt at this, which doesn't use a DNS library yet, and instead just polls on an arbitrary interval.

**Comment by briansmith** [comment]
In the initial description of this issue, there were three cases to consider: one that already worked and two that don't. Of the two cases that don't:

> If the service is an "external" service, then the Destination service should use DNS to discover the addresses for the service[.]

Specifically, this is the case where we have a `Service` definition of type `ExternalName`, e.g. service `foo.my-namespace.svc.cluster.local` has type `ExternalName` as described at https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types. It doesn't seem like anything has been done to address this specific case.

> If the DNS name sent in the query to the Destinations service doesn't end with "cluster.local" or the local cluster domain name, then the Destinations service should skip using the Services API and assume that it is an "external" service[.]

This case is addressed by PR #397.

Another case not previously mentioned is described in issue #392: There are names that could either be completed as "$name.namespace.svc" or they could be resolved as "$name" or, in unusual DNS configurations (see issue #62). The name is ambiguous. Currently we always complete such names as "$name.namespace.svc" but that's not 100% correct.

**Comment by seanmonstar** [comment]
This was addressed in a different way, in #397, by just using the original destination if the authority does not look like a local service name.

**Comment by briansmith** [comment]
> This was addressed in a different way, in #397, by just using the original destination if the authority does not look like a local service name.

I'm reopening this because not all of the cases were addressed by #397 as explained in my previous comment.

**Comment by briansmith** [comment]
I'm going to write up a proposal, mostly in terms of end-user documentation, for how Conduit does service discovery and the differences from how Kubernetes does it by default in #421. I think it would be good to have people review that and make sure we all agree on things before we write more code for this. In particular, I want to make sure @adleong's concerns regarding the earlier work we did here are addressed.

**Comment by olix0r** [comment]
This would benefit from the results of #421

**Comment by wmorgan** [comment]
Is this issue blocked on #421?

**Comment by briansmith** [comment]
> Is this issue blocked on #421?

Partially. The work to support `ExternalNames` services is straightforward and isn't blocked on anything. Dealing with the other remaining case is blocked on #421.

**Comment by klingerf** [comment]
Ok, I can start working on support for `ExternalName` type services in the destination service later today. @briansmith, do you have an ETA for when #421 will happen? Contingent on the output of that, we may need to pull in additional folks to work on whatever arises.

**Comment by klingerf** [comment]
Support for "ExternalName" services is now reviewable, in #490.

**Comment by wmorgan** [comment]
With the `ExternalName` fix in #421, is the only remaining problem to satisfy this captured by this comment?

> There are names that could either be completed as "$name.namespace.svc" or they could be resolved as "$name" or, in unusual DNS configurations (see issue #62), they could be completed with some other suffix. The name is ambiguous. Currently we always complete such names as "$name.namespace.svc" but that's not 100% correct.

If so, rather than writing user-facing docs as part of this release per #421, does it make sense to write up a smaller eng-facing plan that would address this? We can add user-facing docs later, but I would really like to get this fixed in 0.3.1.

**Comment by klingerf** [comment]
@briansmith Have assigned you this issue, since I'm not actively working on it now that the `ExternalName` fix has merged.

**Comment by briansmith** [comment]
The remaining issue is that a name like "example.com" could be "example.com.svc.cluster.local." or "example.com." [1] and the only way we can tell is to first see if there is a service that maps to example.com.svc.cluster.local; if it does then use the IP addresses for the service's pods; if it doesn't then assume it is an external name.

There are longer-term issues (e.g. #62 and #392) that are supposed to be addressed by #421. However, addressing these various edge cases has turned out to be more time-consuming than expected.

I think I found a relatively easy short-term solution for the most urgent issue that "example.com" and similar don't work that doesn't require significant design work (i.e. #421) or significant effort, and which can be used as an incremental step towards a longer-term solution, regardless of the shape of that solution, though it doesn't resolve #62 or #392. Here it is:

In the proxy, when we use the destination service to look up a name, we block all requests for the given name until the destination service gives us at least one IP we can use to make progress. I propose that, instead, after the initial contact with the destination service, if we don't have any IP address for the service then the destination-service-based service discovery should just fail with a NXDOMAIN-like error. When we receive a NSDOMAIN-like error from the destination service then we just use the IP address from `SO_ORIGINAL_DST` like we do for other external names that aren't ambiguous.

Then we can move forward with the 0.3.1 release without resolving #421, with the understanding that we'd resolve #421, #62, #392, and the lack of L7 load balancing for external services in 0.4.0 or so.

[1] It could even map to example.com.$current_namespace.svc.cluster.local." or other things, but that's just a slight generalization of the problem that doesn't affect the shape of any solution, AFAICT.

**Comment by briansmith** [comment]
The remaining case to consider is the case where are names like "example.com" or "example". These names are ambiguous in the normal configuration of a pod. For example, "example.com" could refer to "example.com.svc.cluster.local." or "example.com." depending on whether there is a namespace "com" with a service "example".

The case of "example" is particularly interesting because it could refer to "example." or "example.$current_namespace.svc.cluster.local." Note that "$current_namespace" is the namespace of the pod doing the DNS lookup. For example, if a pod in the "default" namespace does the lookup, then this may resolve to "example.default.svc.cluster.local." This is makes it complicated to do the DNS lookup in the controller, because the controller's DNS configuration (`/etc/resolv.conf`) is configured to have "$current_namespace" would be the Conduit control plane namespace (usually "conduit"). This would require us to implement very low-level DNS processing in the controller; even if we did that it wouldn't address other issues like #62. On the other hand, the proxy's DNS configuration is already set up to do this correctly. Therefore, it makes sense to do the DNS lookup in the proxy.

I investigated whether it is possible to just fall back to the SO_ORIGINAL_DST instead of doing a DNS lookup, since the application presumably already did a DNS loojup. However, it would be non-trivial to implement that fallback logic because of the (very reasonable) way in which the tower-balance load balancing API was designed. Since we want to do L7 load balancing anyway, the proxy needs to have a full(-ish) set of IP addresses for the name and choose amongst them itself based on which is least loaded (from its perspective).

To implement the fallback from using the Destinations service to using DNS in the proxy for such names, we need the control plane to tell the proxy whether or not there is a service with the given name, even if there are no endpoints for that service. This requires extending the protocol used between the controller and the proxy. I have a PR that I am cleaning up now that adds this new `NoEndpoints(exists: bool)` message and modifies the proxy to cope with it.

After that we'll need the Destination service in the control plane to send the new message to the proxy.

Then, the final piece is implementing the DNS logic in the proxy, which I am still working on.

**Comment by olix0r** [comment]
@briansmith Just to get the most recent state of things into the issue..  #631 and #632 are part of the setup for this -- what's remaining when those are merged? i believe we need to move dns resolution into the proxy following this... anything else? do/should we have issues for these remaining tasks?

**Comment by briansmith** [comment]
Let's just continue to use this issue to track the remaining task of adding the DNS resolution into the proxy.

There will probably be some follow-up issues to improve the quality of implementation issues, e.g. reaping Destination and DNS queries that have been unused for a while, which I'll file after the PR for the DNS changes is posted and reviewed.
