### ISSUE TITLE
proxy-deps docker image can pull stale source files into build

### ISSUE THREAD

**Issue by olix0r** [runconduit/conduit#159]
proxy-deps copies in all of the source files so that it can use cargo to fetch dependencies and cache build artifacts.

Then, the proxy image uses proxy-deps as a base image and copies the source directories again.  However, when files are renamed (e.g. `metrics.rs` becomes `metrics/mod.rs`), then both files end up in the build in the final build image, causing the build to fail.

This can be resolved by changing the proxy-deps image to be a multi-stage build that only preserves i.e. `target/`.

**Comment by olix0r** [comment]
The same applies for the _go-deps_ image, which copies the entire source repo.

**Comment by klingerf** [comment]
> The same applies for the go-deps image, which copies the entire source repo.

I might be misunderstanding the issue, but I think this line from Dockerfile-go-deps removes the source code that was copied, before finalizing the base image: https://github.com/runconduit/conduit/blob/master/Dockerfile-go-deps#L14. It leaves only the Gopkg.* files and vendor directories in place.

**Comment by olix0r** [comment]
Ah yes you're right, @klingerf.  It appears the find/delete does this.  I'll see if we can apply the same multistage approach in both (which hopefully avoids the full filesystem walk) and if not, i'll only fix proxy-deps
