### ISSUE TITLE
prometheus dashboard not accessible via k8s proxy

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#183]
When accessing Prometheus via the Kubernetes proxy, most of the dashboard's functionality does not work, because it is served at a non-root URL:
http://127.0.0.1:8001/api/v1/namespaces/conduit/services/prometheus:http/proxy/graph

Some options to mitigate this:
- Document a proxy command to enable access via a root address
- Modify the Prometheus service config (defined in https://github.com/runconduit/conduit/blob/master/cli/cmd/install.go) to enable root url access
- Modify Prometheus' config to use a know url prefix, perhaps with `-web.route-prefix` or `web.external-url`

**Comment by klingerf** [comment]
@deebo91 and I ran into this issue yesterday as well. I think the right solution is to use port-forwarding to access prometheus at a root url. I don't think we should modify the prometheus service config to make it available externally to the cluster. Maybe we just need to document the port-forward approach somewhere in BUILD.md?

**Comment by adleong** [comment]
Is easy access to the Prometheus dashboard something that we want to be part of the product surface area, or are we considering Prometheus to be an internal implementation detail?

**Comment by wmorgan** [comment]
I'd like to treat it as an implementation detail for now (though that might change in the future). But to the extent that it makes debugging easier, then by all means expose it.

**Comment by adleong** [comment]
In that case, I think no action is required.  We can access the prometheus dashboard by using port-forwarding and we don't need to document this in the Conduit docs.
