### ISSUE TITLE
update telemetry service to accept and store tcp data

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#191]
Telemetry service's intake endpoint, `telemetry::Report()` assumes HTTP data:
https://github.com/runconduit/conduit/blob/master/controller/telemetry/server.go#L260

This endpoint should be modified to accept TCP data.

TCP data may include `TargetAddr `, `DurationMs`, and `BytesSent`. Example here:
https://github.com/runconduit/conduit/blob/master/controller/script/simulate-proxy/main.go#L213

**Comment by wmorgan** [comment]
@adleong is this doable in your current telemetry plan for 0.3?

**Comment by adleong** [comment]
I don't think this is doable for 0.3

**Comment by klingerf** [comment]
@rmars Yes, I think we should close this given that the telemetry service doesn't exist anymore, and TCP metrics have been added to the proxy `/metrics` payload.
