### ISSUE TITLE
Update docs about HTTP/1 support

### ISSUE THREAD

**Issue by seanmonstar** [runconduit/conduit#199]
For 0.1, our docs mention that Conduit can only proxy HTTP/2 requests. With 0.2, Conduit can proxy HTTP/1 and TCP as well. We need to audit the docs to remove any references saying otherwise.

- [x] #203 README
- [ ] https://conduit.io/getting-started/
- [ ] https://conduit.io/adding-your-service/

**Comment by olix0r** [comment]
It looks like the docs have been updated
