### ISSUE TITLE
cli tool requires kubectl to be run before it in order for GKE auth to work

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#20]
kubectl apparently does something that triggers a OAuth token refresh when it is expired, which the `conduit` CLI tool doesn't do. We need to figure out what kubectl is doing and do the same in the `conduit` CLI tool.

**Comment by briansmith** [comment]
This might be caused by us using an old version of the client-go library. We should try upgrading to the newest version of client-go to see if that fixes this problem.

**Comment by klingerf** [comment]
I'd be happy to take a stab at that, and agree that it would be great to update client-go. Will assign to myself. We had some issues initially with a bad interaction between client-go and dep, but I can't remember specifically what went wrong. It's also possible that has been fixed now.

**Comment by klingerf** [comment]
Am updating our client-go dependency in #122. And anecdotally, that appears to fix this issue.
