### ISSUE TITLE
Controller Destination graph on service mesh page is sparse with data

### ISSUE THREAD

**Issue by deebo91** [runconduit/conduit#213]
The service mesh page has a graph that shows requests that hit the service discovery endpoint. This graph is sometimes sparse in data and can probably be replaced.

Current state in the emojivoto app.
![Controller Destination pod](https://user-images.githubusercontent.com/2197104/35419322-291741c4-01ec-11e8-8d33-993b96a9903e.png)

**Comment by rmars** [comment]
This graph will be removed (#244)
