### ISSUE TITLE
factor out metrics serving in controller processes

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#228]
Code to initialize the scrapable `/metrics` endpoints are repeated (and slightly different) across the various controller components. We could centralize this for clarity and consistency.

```bash
$ grep -R "promhttp.Handler()" .
./controller/cmd/public-api/main.go:		http.Handle("/metrics", promhttp.Handler())
./controller/cmd/destination/main.go:		http.Handle("/metrics", promhttp.Handler())
./controller/cmd/tap/main.go:		http.Handle("/metrics", promhttp.Handler())
./controller/cmd/proxy-api/main.go:		http.Handle("/metrics", promhttp.Handler())
./controller/cmd/telemetry/main.go:		http.Handle("/metrics", promhttp.Handler())
./web/main.go:		http.Handle("/metrics", promhttp.Handler())
```

**Comment by alenkacz** [comment]
I'll take this one...

**Comment by briansmith** [comment]
I think most or all `/metrics` endpoints will be completely removed when #351 is fixed. In fact, the fix for #351 is exactly to remove all the `/metrics` endpoints and the code that implements them.

**Comment by alenkacz** [comment]
ok :) then I'll take something else :) thanks for the heads up

**Comment by olix0r** [comment]
@briansmith Can you elaborate on why?

There are important per-process stats (like number of goroutines, for instance) that are useful to export. Traffic stats are obviously very important, but I don't think that we want to limit ourselves to _only_ being able to use these stats, unless there's a really compelling reason.

**Comment by briansmith** [comment]
If we are currently already exporting non-traffic stats, then OK, let's keep these endpoints for the non-traffic stats. Last time I looked, I didn't notice any non-traffic stats, but I admit I didn't look super closely either. For example, I don't remember seeing us export statistics for number of goroutines, but I might could very well have overlooked that.

My main goal is to use the proxy for things the proxy can do, and avoid duplicating proxy functionality, as much as possible.

**Comment by siggy** [comment]
The Prometheus HTTP GO client gives us a lot of per-process stats for free. Here's a list:
https://gist.github.com/siggy/66b799271fe168edda516cdd50447466

These metrics will help to power a "Conduit Health" dashboard, described in this ticket and associated doc: #420.

@alenkacz In case you've stopped following this thread, this ticket is still open for business. Feel free to work on it if you like.

**Comment by briansmith** [comment]
> The Prometheus HTTP GO client gives us a lot of per-process stats for free. Here's a list:
> https://gist.github.com/siggy/66b799271fe168edda516cdd50447466

Thanks. Thus, my comment in https://github.com/runconduit/conduit/issues/228#issuecomment-370259689 is totally wrong and should be ignored. Sorry for the noise.

> @alenkacz In case you've stopped following this thread, this ticket is still open for business. Feel free to work on it if you like.

+1

**Comment by alenkacz** [comment]
👍
