### ISSUE TITLE
Remove pod-level metrics from telemetry pipeline

### ISSUE THREAD

**Issue by adleong** [runconduit/conduit#262]
Blocked by #261 

Stop writing to the `source` and `target` labels in Prometheus.

**Comment by adleong** [comment]
Note that we cannot remove the `source_ip` field from the request context in the telemetry report proto because the proxy does not know which deployment an IP belongs to.  It is the controller that must determine this.

**Comment by hawkw** [comment]
I believe this was closed in #304 as well:

https://github.com/runconduit/conduit/blob/2015d992cc9cdc6f32bb132add5118b7862cd455/controller/telemetry/server.go#L407-L412
