### ISSUE TITLE
Configuration settings should take units in the value, not put units in the setting name

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#27]
Consider `CONDUIT_PROXY_EVENT_BUFFER_CAPACITY`. What units is this setting measured in? Currently the units are implicitly bytes, e.g. `CONDUIT_PROXY_EVENT_BUFFER_CAPACITY=10000` means 10,000 bytes. Instead of having implicit units, we should use explicit units so we can write, e.g. `CONDUIT_PROXY_EVENT_BUFFER_CAPACITY=10kb` (for base-2 kilobytes) or `CONDUIT_PROXY_EVENT_BUFFER_CAPACITY=10000b` (for bytes), etc.

Similarly we have `CONDUIT_PROXY_METRICS_FLUSH_INTERVAL_SECS`. This is better because the name of the setting gives the units so one doesn't have to guess. However, we've already run into a case during testing where we want to use a sub-second unit. This setting should instead by named `CONDUIT_PROXY_METRICS_FLUSH_INTERVAL` and accept values with units specified, e.g. `10s` for 10 seconds or `200ms` for 200 milliseconds.

Similar concerns apply to other settings, not just in the proxy, but also in the other components.

**Comment by hawkw** [comment]
Okay, I wrote a lot of these configuration settings, so I'd be happy to fix this.

**Comment by briansmith** [comment]
Great. I'll merge b/env5 (#24,  #25, #26) as soon as I get on a network where I can re-verify that everything is working in minikube. (This issue is a follow-up to those PRs.)

**Comment by hawkw** [comment]
Sounds good to me. Do you think we ought to interpret these settings with a default unit in cases where one is not provided (so as to not break existing configs), or treat missing units as a parse error (cc @olix0r)?
