### ISSUE TITLE
Stop using port 8001 as the default port for `conduit dashboard`

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#291]
`kubectl proxy` uses port 8001 as its default. Thus, any time the user is running `kubectl proxy` then `conduit dashboard` will fail, at default settings, since the port will be in use already. A very simple way to prevent this failure more often is to use a port other than 8001 by default. 

Especially now that https://github.com/runconduit/conduit/pull/249 has landed we could probably even use a random port by completely avoid collisions. Whether it makes sense to use a random port or a different fixed port by default depends on whether we want to support the user bookmarking the URL for the proxied dashboard. I don't think we need to support the bookmarking, especially because it is likely that the URLs will change in the future when we add better TLS support to the control plane.

**Comment by pcalcado** [comment]
Agree, binding to `:0` seems to be a nice solution. We just need to make sure that there aren't problems running many k8s proxies.

**Comment by wmorgan** [comment]
Not a blocker for 0.3, but keeping it in the milestone for now to see if we get to it.
