### ISSUE TITLE
fix web app dev build

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#301]
The instructions for running `web` in `BUILD.md` no longer work. Running `bin/go-run web` from the root of the repo fails because it cannot find the template and static dirs, as the default params assume the process is started from the `web` subdir:

```bash
$ bin/go-run web --help
...
  -static-dir string
    	directory to search for static files (default "app/dist")
  -template-dir string
    	directory to search for template files (default "templates")
```

This results in a null pointer exception, as the `template` var is nil:
https://github.com/runconduit/conduit/blob/a9d4a3d74e6912889a8056a3b788d281720a3fa2/web/srv/server.go#L115

Action items:
1) Update `BUILD.md` with correct build/run instructions:
  ```bash
  cd web
  ../bin/go-run .
  ```
2) Modify `loadTemplate` to return an error if the template is not found:
https://github.com/runconduit/conduit/blob/a9d4a3d74e6912889a8056a3b788d281720a3fa2/web/srv/server.go#L103

**Comment by hawkw** [comment]
![screen shot 2018-02-08 at 12 01 02 pm](https://user-images.githubusercontent.com/2796466/35995331-d94a25e4-0cc7-11e8-8572-b920077d73f2.png)
