### ISSUE TITLE
Inject the Conduit proxy into all Conduit control plane pods

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#311]
The control plane itself should have all the observability, reliability, and security benefits that any Conduit-managed service would have. For example, we should be able to see request success rates and latencies for the private API and the public API and for the Web UI in the Conduit web UI and in `conduit stats`. Further, the way the control plane is secured (via TLS, in particular) should be done in the same way it is done for the data plane. To do this without duplicating work between the control plane code (in Go) and the proxy code (in Rust), the proxy should be injected into all the control plane pods and as much as possible everything should work as though the control plane is part of the data plane.

There may be bootstrapping-specific stuff we need to address since the proxy will both be proxying the control plane and using the control plane's private API as a client. See #302.

/cc @olix0r @adleong

**Comment by deebo91** [comment]
> we should be able to see request success rates and latencies for the private API and the public API and for the Web UI in the Conduit web UI and in conduit stats

Currently, the private API and public API reside in the same pod. If we want to see stats for each of those APIs we may need to break up the two services and place them into their own pods. Is that something we should do?

**Comment by briansmith** [comment]
> Currently, the private API and public API reside in the same pod. If we want to see stats for each of those APIs we may need to break up the two services and place them into their own pods. Is that something we should do?

Really my point is that there are a lot of benefits to using the proxy within the controller; some of them won't be realized immediately though. I wouldn't do any work related to metrics or any particular justification except the TLS-related ones w.r.t. this issue.

Once we add back the ability to do hostname- (and path-) based stats then we'll have the ability to separate private API statistics from each of the APIs even if they stay in the same pod. There are potentially security and/or scaling and/or maintainability advantages to putting them in separate pods but we should decide that separately.

**Comment by adleong** [comment]
The sidecar model generally assumes that pods are somewhat atomic.  That is, intra-pod traffic generally does not go through the proxy and therefore metrics for that traffic is not gathered.  With our current architecture where all controller components run in the same pod, this means that we will be able to get metrics for external APIs only (proxy-api and public-api).  I think this is a perfectly reasonable stepping stone and will improve in the future when we split the controller pods up, allowing each individual component to have its own dedicated proxy sidecar.
