### ISSUE TITLE
create distinct Query and QueryRange endpoints in Telemetry service

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#312]
The telemetry service exposes a single `Query()` endpoint to retrieve both timeseries and single data point metrics. Under the hood `Query()` is calling Prometheus' `Query()` or `QueryRange()` endpoints, depending on the input.

We should modify the Telemetry service (and possibly the APIs above it) to break out timeseries and non-timeseries into separate endpoints.

Followup from https://github.com/runconduit/conduit/pull/298#discussion_r167034988

**Comment by klingerf** [comment]
The telemetry service was removed in #757; closing this.
