### ISSUE TITLE
Add "is on latest version" do conduit check

### ISSUE THREAD

**Issue by pcalcado** [runconduit/conduit#314]
As part of the tests performed in `conduit check`, we should warn the user if they are running an older version on Conduit ion both server and client.

Output mockup:
```shell
pcalcado@arbeitsziege.local:$ conduit check
kubectl: is in $PATH............................................................[ok]
kubectl: has compatible version.................................................[ok]
kubectl: can talk to Kubernetes cluster.........................................[ok]
kubernetes-api: can initialize the client.......................................[ok]
kubernetes-api: can query the Kubernetes API....................................[ok]
conduit-api: can retrieve status via gRPC.......................................[ok]
conduit-api[telemetry]: control plane can use telemetry service.................[ok]
conduit-version: CLI is up-to-date..............................................[ok]
conduit-version: control plane is up-to-date....................................[FAIL]  -- Server is running version [0.1], the last version is [2.0]

Status check results are [FAIL]
pcalcado@arbeitsziege.local:$ echo $?
1
```

**Comment by ahume** [comment]
Hi, looking at this from a good-first-issue perspective and have a couple of questions.

* Do you have a mechanism in mind for discovering the latest version? (E.g checking a github releases, or some other, endpoint).
* I assume the latest version is always the same for both CLI and server?
* Was experimenting with extending `pkg/version/version.go` to implement the `StatusChecker` interface, as the other checks do. But wondering if you had another way of structuring this in mind?

**Comment by klingerf** [comment]
Hey @ahume, awesome! I think this would be a great one to tackle, and you're totally on the right track.

* For determining the current version, we should use https://versioncheck.conduit.io/version.json
* The notion of "current version" is universal, does not vary between the CLI and the public API
* Updating `pkg/version/version.go` to support the `StatusChecker` interface seems like exactly the right approach to me.

Don't hesitate to reach out if you have any other questions along the way.
