### ISSUE TITLE
What to do with conduit stat options after removing metric aggregation types?

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#316]
Merging #304 removed the `conduit stat pods` option from `conduit stat`. When we merge #315, the `conduit stat paths` option will also be removed, meaning that `conduit stat deployments` is the only valid command. However, running this command will still require the user to type `conduit stat deployments`, although there are no other options. 

Should we change `conduit stat` to default to deployments, or just completely remove the option from the UI? In the short term, that would make the tool easier to use, but if we are planning on adding per-path or per-pod metrics back to `conduit stat` later, the UI would have to be changed again...

**Comment by wmorgan** [comment]
At this point forward compatibility is not a priority. I think the most natural thing is to have "conduit stat" and "conduit stat deployments" both do the same thing, at least for the time being.

**Comment by briansmith** [comment]
I suggest we remove `conduit stat` completely, iterate on the presentation of the same info in the web UI, and then add `conduit stat` back once we know better what people want to see in its output.

**Comment by wmorgan** [comment]
I think it's important to keep `conduit stat` because it's a very easy demonstration of Conduit's end-to-end telemetry pipeline. In fact, I think it's one of the most coherent demonstrations of value that Conduit 0.3 will have. Personally I'm not really worried about "what people want to see in its output"; there will be some iteration but I am pretty confident in the basics (service-level success rates, etc.) we have in place now.

**Comment by briansmith** [comment]
OK. I think I'm not understanding how the intended use of `conduit stats` is different than what's possible with the web UI. In any case, I definitely don't hold a strong opinion on it.

**Comment by pcalcado** [comment]
I like the idea of removing it instead of making both with and without target. I think that more interesting filters will be by namespace and labels, right now there's no reason to overload newcomers with the extra argument.
