### ISSUE TITLE
`/api/metrics` endpoint fails when many pods present

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#328]
per https://github.com/runconduit/conduit/pull/323#pullrequestreview-95603962, where querying:
```
http://localhost:8084/api/metrics?window=10m
```
... this returns `datapoints: []` or fails if many pods are present. reproduced using `simulate-proxy` without a pod limit.

**Comment by wmorgan** [comment]
Let's try and reproduce this once pod telemetry data has been removed.

**Comment by klingerf** [comment]
@siggy @adleong -- can we verify that this is no longer an issue now that the telemetry optimizations have merged?

**Comment by adleong** [comment]
Testing against an install with 10 deployments with 10 replicas each I do not see this error.

**Comment by siggy** [comment]
Successful test against 72 pods, running locally in Docker For Mac

### Setup

```bash
docker-compose build && docker-compose up -d
bin/go-run controller/script/simulate-proxy --kubeconfig ~/.kube/config --addr localhost:8086 --sleep 100ms
```

### Results

```bash
$ curl -s http://localhost:8084/api/metrics?window=10m | jq '.metrics | length'
216

$ time curl -so /dev/null http://localhost:8084/api/metrics?window=10m
real	0m0.801s
user	0m0.013s
sys	0m0.012s

$ time curl -so /dev/null "http://localhost:8084/api/metrics?window=10m&timeseries=true"
real	0m4.118s
user	0m0.014s
sys	0m0.013s
```

Prometheus running locally in Docker For Mac required 240% cpu, and 500MB mem.
