### ISSUE TITLE
conduit executables are very large

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#352]
conduit-0.2.0-linux is over 27MB.

Simply running `strip` on it results in a ~17MB executable.

At least we should consider building the Go executables with the `-s` and `-w` linker flags as explained in https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/. That post notes "Interestingly, what gets stripped is only the DWARF tables needed for debuggers, not the annotations needed for stack traces, so our panics are still readable!"

This would make the download of the `conduit` executable snappier and would make all container operations a bit snappier as well.

28,695,438 conduit-0.2.0-linux
17,849,120 conduit-0.2.0-linux-stripped

**Comment by wmorgan** [comment]
If it's as easy as adding some build-time flags, I'd like to consider this for 0.3.

**Comment by briansmith** [comment]
#367 gets them down to ~18MB. That still seems hugely excessive considering how little the CLI actually does. However, I don't have time to investigate it further.

**Comment by wmorgan** [comment]
Cool!
