### ISSUE TITLE
The proxy shouldn't ask the controller to resolve IP addresses, especially localhost addresses 127.0.0.1 and ::1

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#357]
I understand that at some point in the future we might try to implement some interesting logic when the proxy gets an IP address as the destination, and that interesting logic would probably be better implemented in the controller. However, I think the implementation of that logic is quite far out and maybe won't ever be needed. Unless/until we get closer to that, we should just have the proxy resolve IP addresses internally, without contacting the controller.

In particular, we definitely shouldn't ask the controller to resolve 127.0.0.1 and ::1. Applications use these loopback addresses to guarantee that their networking traffic is local for security reasons (especially) and performance reasons. The interesting logic we intend to support by passing IP addresses to the controller won't be able to be done for loopback addresses without serious risk of violating the security assumptions the proxied application is making. Avoiding resolving these addresses through the controller is an important step towards ensuring the proxy doesn't violate any security assumptions.

/cc @seanmonstar @adleong

**Comment by adleong** [comment]
:+1:

**Comment by seanmonstar** [comment]
The changes in #397 means that the destination service is no longer asked about IP addresses in the authority. However, it doesn't do anything with special addresses.

**Comment by briansmith** [comment]
I think we can call this "Fixed" by just adding some more `none()` tests that cover IP addresses (IPv4 and IPv6), especially but not only `127.0.0.1` and `::1`, to `test_normalized_authority()`.

(`localhost` and other non-IP-address issues are described elsewhere.)
