### ISSUE TITLE
Control pod stats appear in web UI when proxy is injected into control pod

### ISSUE THREAD

**Issue by dadjeibaah** [runconduit/conduit#370]
After running install with the newly added functionality which injects an "mesh" proxy into the control pod. We see telemetry stats for the "mesh" proxy in the web UI. At first glance, this may seem confusing to a user when they install their services in a separate namespace. One solution is to either disable mesh telemetry stats in the short term and revisit how we would like for that information to show up in the UI. 

__Using emojivoto as a test environment, we see that `conduit/controller` shows up in the UI__

<img width="991" alt="screen shot 2018-02-16 at 10 05 37 am" src="https://user-images.githubusercontent.com/2197104/36322226-66330d60-1301-11e8-8b77-f2d85d09d7f7.png">

__Clicking on the `emojivoto/web` deployment, we see `conduit/controller` stats show up again__

<img width="801" alt="screen shot 2018-02-16 at 10 06 20 am" src="https://user-images.githubusercontent.com/2197104/36322261-86f799a8-1301-11e8-8c9b-28d43827e697.png">

__However, when we click on the link to view the `conduit/controller` deployment stats, we get an error__

![failed-controller-stats](https://user-images.githubusercontent.com/2197104/36322333-c6a3a3ee-1301-11e8-9ae9-901c93c4a7bb.gif)
 
/cc @briansmith

**Comment by briansmith** [comment]
I suggest we close this as works-as-intended. It is very useful for debugging purposes to see the traffic from the proxies to the control plane, both the quantity and the success rate. 

Earlier Conduit releases there was way too much traffic between the proxy and the control plane and that's now being addressed in 0.3, and such visibility would have been useful for recognizing that earlier on.

It's especially useful to see when the pod has been disconnected from the control plane. "Why doesn't service discovery work? Oh, I see, traffic between this pod and the Conduit control plane has been failing." Very useful.

Later people will need to tune metrics, tracing, logging, etc., making performance vs. available information decisions, and seeing this will be useful for that too. "Oh, we're generating 100mpbs of traffic for metrics? Why? Oh, I see, I set knob X to a crazy value."

**Comment by deebo91** [comment]
@adleong would like to here your thoughts on this. Had a quick chat with @wmorgan and he mentioned that we should not show the stats from showing up in the UI. This makes me wonder. Should we avoid collecting internal proxy stats i.e. adding functionality to skip sending data prometheus or should we continue to sending stats through prometheus and make avoid making the stats available through the public api?

**Comment by siggy** [comment]
My 2 cents: it can be useful to look at telemetry data about Conduit itself, though this doesn't mean we need to show it in the conduit dashboard. Via #420, we're going to experiment with a `Conduit Viz` and `Conduit Health` dashboard. The latter is intended to use this very telemetry data to show the health of Conduit itself.

**Comment by deebo91** [comment]
That's right. So it sounds like we want do want to continue recording internal proxy telemetry. That would mean that we can just remove internal proxy telemetry from the from the UI then. That is helpful @siggy thank!

**Comment by adleong** [comment]
All of this is going to change in 0.4:
* Proxies will no longer be pushing metrics to the telemetry service, but instead will be exposing metrics to be scraped (#425)
* The deployment detail page may be going away in favor of a grafana dashboard (#420)

I suggest that in the short term we disable telemetry reporting in the controller's proxy.

In the long term I agree that this data is valuable but it's different from the data currently displayed on the deployment detail page. Once we have prometheus collection working, I think we should have prometheus labels that differentiate the controller's proxy from data plane proxies so that we can treat that data separately.  The deployment grafana dashboard could easily have a graph showing communication to the controller.

**Comment by siggy** [comment]
Per offline convo, for now we can filter these metrics out at a read time, either in the telemetry service or public api.

**Comment by briansmith** [comment]
@adleong wrote:
> I suggest that in the short term we disable telemetry reporting in the controller's proxy.

@siggy wrote:
> Per offline convo, for now we can filter these metrics out at a read time, either in the telemetry service or public api.

Unless there is a known problem doing, I would prefer to consider this a UI issue and do the filtering as close to the UI as possible. That is, I think it is better to report the numbers and then filter the things out in the UI. If we want to do the filtering in the public API to keep the CLI and web UI consistent, that's OK with me.

**Comment by olix0r** [comment]
My IRL suggestion was that the telemetry read API be modified to just never return deployments in the same namespace as the controller. This seems like a good-enough solution, given that the telemetry service is being removed in 0.4
