### ISSUE TITLE
Provide a way to break out metrics by a TLS dimension

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#388]
One requirement for the proxy privacy project is that the UI should be able to break out metrics according to whether TLS was used. For example, we should be able to see separate request latency and separate success rate numbers for a pod's TLS traffic and for its non-TLS traffic. The user might also prefer to see these combined into overall metrics (TLS + non-TLS).

* How should this be done in the Web UI?
* How should this be done in `conduit stat`?

We should design the UI early on while waiting for the underlying foundational TLS work to be done, since the UI design itself might be non-trivial, and because the changes to the web UI and/or `conduit stat` to implement such API might be non-trivial.

/cc @wmorgan, who might suggest more specific requirements. I've set the target milestone to 0.4 based on my understanding of the desired prioritization.

**Comment by klingerf** [comment]
@wmorgan / @olix0r Is this issue solved by the `SECURED` column in the CLI output and in the web UI stat tables? Or is there additional design work that needs to happen for the TLS feature?

**Comment by wmorgan** [comment]
Yes, the design work in this issue is captured by the changes already in master to the CLI, Grafana, and web UI.

**Comment by klingerf** [comment]
Great, thanks @wmorgan -- am going to close this.
