### ISSUE TITLE
Support HTTP/1.1

### ISSUE THREAD

**Issue by adleong** [runconduit/conduit#4]
Add support for HTTP/1.1 including automatic protocol upgrade from HTTP/1.1 to HTTP/2.

**Comment by xiaods** [comment]
it need auto generate tls keystone.

**Comment by xiaods** [comment]
https://github.com/hjr3/weldr

**Comment by xiaods** [comment]
@adleong any some design for this proposal, i would like to involve it.

**Comment by olix0r** [comment]
Hi @xiaods! We've still fleshing out our plans in #41.

**Comment by xiaods** [comment]
@olix0r got it. thanks for remind.

**Comment by olix0r** [comment]
Closing this issue in favor of #130, which is more narrowly scoped. Additional HTTP/1 improvements will follow.
