### ISSUE TITLE
Incoming connection protocol discrimination needs to consider more than the first few bytes of incoming connections

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#417]
At first we were assume that we would be able to distinguish the following kinds of traffic based on the initial bytes and sort it into the following cases:
1. Plaintext HTTP/1.x traffic.
2. Plaintext HTTP/2.x traffic.
3. TLS traffic.
4. Other non-HTTP, non-TLS TCP traffic.

However, for #3 there are actually two cases: TLS traffic for which the Conduit proxy should process terminate TLS itself, and TLS traffic that should be forwarded opaquely (like non-HTTP, non-TLS traffic) to the proxied service. In order to distinguish between these two cases I want to use the contents of the TLS ClientHello extensions.

These extensions can be many bytes deep within the initial sequence of bytes that the client sends in the TLS handshake. Previously we assumed that we would be able to do protocol discrimination by only looking at the first few client-sent bytes, but this isn't the case here. However, this is a simpler case than #339.

@seanmonstar Given the current state of thing and/or the state of things after #339 is fixed, how problematic would it be to need to read dozens or hundreds of initial client-sent bytes before making the protocol determination?

**Comment by olix0r** [comment]
@briansmith I'm not sure how practical/realistic this is, but this is how I've been envisioning protocol detection:

```
       +--------+
       | accept |
       +--------+
         | (1)
         V
       +---------------------------------------------+
       |                transport hint               |<------|
       +---------------------------------------------+       |
         | http    | tls (2)             | tcp               |
         |        +------------+         |                   |
         |        | hello hint |         |                   |
         |        +------------+         |                   |
         |         |    | (3)            |                   |
         |         |  +-----------+      |                   |
         |         |  | replay    |----->|                   |
         |         |  +-----------+      |                   |
         |         |                     |                   |
         |        +-------------+        |                   |
         |        | protocol    | (4)    |                   |
         |<-------| negotiation |------->|                   |
         |        +-------------+        |                   |
         |                 | (5)         |                   |
         |                 |-------------~-------------------|
         |                               |
         |                               |
        ...                             ...
         |  CONNECT/upgrade (4)          |
         |------------------------------>|
         |                               |
        ...                             ...
```

1. When a peer connects to the proxy, it attempts to detect the protocol. For the sake of
   brevity, I've combined the HTTP/1 and HTTP/2 cases.

2. If we detect that the connection has TLS records, all records are buffered until the
   clienthello is detected (or we otherwise determine whether the stream should be
   handled).

3. If the stream should not be encoded, we treat the stream as a raw tcp stream, prefaced
   with the "replayed" buffered records that were already processed.

4. If we should decrypt TLS traffic and the client does ALPN, we know whether the protocol
   is a supported HTTP protocol or an unsupported raw stream.

5. If we should decrypt TLS traffic and ALPN is not present, we could try to handle the
   decrypted stream as an unknown stream. I doubt that this is important until we have to
   support non-proxy TLS clients.

---

I think the crux of this depends on if `(3)` is actually practical -- can we decode all of the TLS records up to a clienthello and then, if the value is not what we expected, create a new stream that replays them until exhausted and then consumes from the original stream?

**Comment by briansmith** [comment]
In general, your explanation sounds correct.

> If we detect that the connection has TLS records [...]

I interpret this to mean "If the first small number of bytes look like the start of a TLS connection," and I agree.

> all records are buffered until the clienthello is detected

Correct. Note that the ClientHello is the first record so we don't have to buffer more than one record. In the common case one `recv(...)` of ~1kb will be sufficient to get the whole ClientHello, however we'll of course still have to handle the edge cases up to 16kb or so. If it is problematic to initially allocate a 1KB buffer than then grow it up to 16KB, we can consider some optimizations in the short-term with the knowledge that Conduit-originated ClientHellos will always be <1kb (or some similarly low size).

> If the stream should not be encoded, we treat the stream as a raw tcp stream, prefaced
> with the "replayed" buffered records that were already processed.

Even if we don't decode the traffic, I think we may want to differentiate the underlying protocols: Did it look like TLS that we're passing through? If so, did it have an ALPN and/or SNI? That way we can break down the metrics in more detail. I'm not sure if that's a useful complication, however.

The important thing, as far as this issue is concerned, is that the ALPN and "client hello hint' will be in the ClientHello extensions, which are not at the beginning of the ClientHello record.

**Comment by seanmonstar** [comment]
So, what is the action of this issue? To add detection of TLS to the protocol detection feature?

**Comment by olix0r** [comment]
@seanmonstar that's definitely at least a part of it...  I don't entirely understand how the proxy should advertise ALPN, which impacts how protocol detection will/can work. I've been writing a (somewhat aspirational) _life of a request_ doc that I hope can help make some sense of the proxy's routing logic, particularly as it applies to protocol detection/transparency. I'll share this in a PR for discussion. This definitely seems like a case where we need to do some more up-front design to make sure we're not missing big details.

**Comment by seanmonstar** [comment]
@briansmith what would you expect the action is? Is this saying that the protocol detection should be changed from just a peek to a type that *may* want to keep reading and buffering? As a step before we add TLS detection?

**Comment by briansmith** [comment]
Yes, that sounds right. After we capture the first few bytes of a connection, if that connection is detected as TLS, then there should be some kind of callback that can say "I need at least N more bytes of input to continue protocol detection" or "I've decided we'll terminate TLS" or "I've decided we won't terminate TLS so forward the buffered bytes and all remaining bytes."

**Comment by seanmonstar** [comment]
Would a PR to fix this issue include the TLS termination decision? Or you're saying that is what needs this refactoring?

**Comment by briansmith** [comment]
> Would a PR to fix this issue include the TLS termination decision? Or you're saying that is what needs this refactoring?

That's what needs this refactoring.

Note that when we're terminating TLS, we'll also need to support two-level protocol detection, e.g. HTTP/2 within TLS vs HTTP/1 within TLS.

**Comment by seanmonstar** [comment]
@briansmith would you need a single `&[u8]` to do the TLS determination?

I'm wondering if I need to keep growing a single contiguous buffer (and thus have to copy previous reads), or if the buffer can actually be a list of smaller buffers, so reserving more space doesn't need to copy previous reads?

Or would we never need more than a maximum size, and should just allocate that to begin with (after the initial peek)?

**Comment by briansmith** [comment]
> @briansmith would you need a single `&[u8]` to do the TLS determination?

Rustls doesn't use abstractions like `Bytes` directly so at some point we might coalesce whatever is available into a single buffer. However, that could happen in the Rustls-Tokio adapter or in the TLS logic itself.

> I'm wondering if I need to keep growing a single contiguous buffer (and thus have to copy previous reads), or if the buffer can actually be a list of smaller buffers, so reserving more space doesn't need to copy previous reads?
> 
> Or would we never need more than a maximum size, and should just allocate that to begin with (after the initial peek)?

Most of the time, given the small number of bytes from the initial `peek`, we'll be able to determine exactly how many bytes are needed to read the entire ClientHello, so usually the callback could return the presumed needed number of bytes and then you could allocate a single buffer of that size. it is possible that the ClientHello could be fragmented into multiple TLS records which would make it impossible to predict in advance how many more bytes are needed exactly, but that is *very* rare. I think we should optimize for the case where the callback can tell us exactly the right number of bytes and do one allocation, and then support growing that allocation, but not worry about the overhead of growing that initial allocation for the edge case (which will, probably, never happen, except in attack scenerios or conformance checking tools).
