### ISSUE TITLE
Proxy should be able to determine its own deployment

### ISSUE THREAD

**Issue by adleong** [runconduit/conduit#426]
When the proxy is injected, it should be configured with a set of prometheus labels that are added to all exposed metrics.

**Comment by briansmith** [comment]
> message Deployment {
>   string namespace = 1;
>   string name = 2;
>   string kind = 3; # Deployment or Job or ReplicaSet or etc. 
> }

The namespace will always be the same, so the response doesn't need to include the namespace as a separate item.

> rpc GetDeployment(Pod) returns Deployment

Why not have `GetTagetDeploymentLabel(Pod) returns string` (or the moral equivalent) instead?

**Comment by briansmith** [comment]
Actually, why can't `conduit inject` do this by setting an env. var. in the proxy container configuration? When it injects the container into the pod, it already knows what Deployment (or replicaset or whatever) the pod is contained in.

In particular, I don't think that we should require a proxy instance to wait for a roundtrip with the controller to get this information, especially since the goal is to reduce interaction between the proxy and the controller anyway.

**Comment by olix0r** [comment]
Is there a way to make this determination in Prometheus? Specifically, since Prometheus knows the pod name when it reads metrics, I'd imagine there might be a way to determine the pod's deployment (or rc or whatever) and add the appropriate label at write-time. @siggy @brancz

**Comment by adleong** [comment]
@briansmith that's a good point, I hadn't thought of that.  Implementing this as part of `conduit inject` (and later as part of the mutating webhook) seems like it should work and avoids the need for a new API.

**Comment by briansmith** [comment]
> Is there a way to make this determination in Prometheus? Specifically, since Prometheus knows the pod name when it reads metrics, I'd imagine there might be a way to determine the pod's deployment (or rc or whatever) and add the appropriate label at write-time. @siggy @brancz

Which pods are in which deployments could change over time as new deployments are deployed.

**Comment by adleong** [comment]
@olix0r the pod's owner is theoretically knowable by Prometheus, but I don't know if it's exposed at all.  It does not appear to be mentioned here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod

**Comment by briansmith** [comment]
> Which pods are in which deployments could change over time as new deployments are deployed.

In particular, there are potential race conditions:

1. Pod foo.ns is deployed in deployment1
2. Pod reports telemetry to Prometheus.
3. Pod foo.ns is (re)deployed in deployment2
4. Prometheus tries to determine which deployment foo.ns is deployed in, and gets "deployment2", but the metrics were for foo.ns from "deployment1."

**Comment by olix0r** [comment]
@adleong is this issue still valid, as described? We've discussed requiring that the proxy take a set of process-global prometheus labels? Is that required for 0.4.0?  Should we start a new issue?

**Comment by adleong** [comment]
I think this issue is still valid although the implementation has changed from what is in the description here.  #448 (using a prometheus labels env var) accomplishes this and is required for 0.4.0.

**Comment by olix0r** [comment]
@adleong Do we have an issue that tracks the changes needed in the proxy to accept this configuration? If this is that issue, can you please update the description? Thanks.

**Comment by adleong** [comment]
Yes, it's part of https://github.com/runconduit/conduit/issues/425 and called out in the description.
