### ISSUE TITLE
Update Prometheus config to scrape data-plane pods

### ISSUE THREAD

**Issue by adleong** [runconduit/conduit#428]
Update Conduit's Prometheus config to scrape from all pods with the label: `conduit.io/control-plane-ns = {{conduit-namespace}}`.

The scrape config should do any necessary write-time processing (aggregations, recording rules, relabeling, dropping labels, etc.) to support the queries that Conduit will want to do.  These include:

# Topline

* Top line request volume `inbound_requests_total{target_<X>=foo}`
* Top line SR `inbound_responses_total{target_<X>=foo, classification=success}`
* Top line latency `inbound_response_latency{target_<X>=foo} by le`

Where `<X>` is a pod owner type.

# Inbound

* The above metrics per inbound service `outbound_<metric>{target_<X>=foo} by (target_service)`
* For a given inbound service, the above metrics per upstream `outbound_<metric>{target_<X>=foo, target_service=bar} by (source_<Y>)`

Where `<X>` and `<Y>` are pod owner types.

# Outbound

* The above metrics per outbound service `outbound_<metric>{source_<X>=foo} by (target_service)`
* For a given outbound service, the above metrics per downstream `outbound_<metric>{source_<X>=foo, target_service=bar} by (target_<Y>)`

Where `<X>` and `<Y>` are pod owner types.

# Per-pod

* Per-pod metrics `inbound_<metric>{target_<X>=foo} by (instance)`

Where <X> is a pod owner type.

**Comment by adleong** [comment]
Note that all labels required for these queries will be provided by the proxy (as per #425) except for:

* `instance`: which can be provided by the prometheus scrape config
* `classification`: this should be derived from `status_code` and `grpc_status_code` (If grpc_status_code exists then 0 means success and any other value means failure.  If grpc_status_code does not exist then status_code matching 5XX is failure and any other value is success.)  Is this possible using a label_replacement?  Otherwise, can this logic be applied at read time with a particular query?

We should also determine which (if any) labels can be dropped to reduce the number of timeseries that we need store.

**Comment by adleong** [comment]
Blocked on either #425 (for real data) or #498 (for fake data)

**Comment by adleong** [comment]
I would like signoff here from @olix0r and @siggy that the labels and queries described here are sane and a good starting point.

**Comment by olix0r** [comment]
Blocked on https://github.com/runconduit/conduit/pull/536
