### ISSUE TITLE
MongoDB connections from injected pods keep growing and growing

### ISSUE THREAD

**Issue by bourquep** [runconduit/conduit#434]
Yesterday evening, I injected Conduit v0.3.0 into all my production services so I could observe the system behavior with real traffic (off-peak traffic, but still more than on my test cluster). Everything was running smoothly so I went to bed and woke up early in order to assess the situation before morning rush hour knocked at my services' door.

Conduit itself was still up and running, so were all my services. However, I noticed that my MongoDB database was saturated with connections:

<img width="797" alt="mongo connections" src="https://user-images.githubusercontent.com/65096/36597906-9868c4c4-1878-11e8-86ab-2c4744ed3615.png">

This is very unusual, as the number of active connections to Mongo has always stayed within the 300..500 range. The rise of number of connections started pretty much exactly when I injected Conduit in my services.

In order to fix this, I tried (in that order):

1. "Uninject" Conduit from all the services, confirmed that they were no longer green in Conduit Dashboard, waited a few minutes and the number of Mongo connections did not drop.
2. Restarted all Conduit pods (`kubectl delete po --all -n conduit`), waited a few minutes and the number of Mongo connections did not drop.
3. Step down the primary Mongo node, so another node from the replica set would become primary, forcing all Mongo clients to reconnect. This is what worked.

I was expecting step 1 to work, as my understanding was that the Conduit proxies live as a sidecar within my service pods, so I expected that killing the pods would also kill the proxies, freeing up Mongo connections.

When I saw that it didn't work (after waiting ~5 minutes, to make sure the connections reported by Mongo weren't in some "pending close" TCP state), I thought that it might mean that my understanding of the Conduit architecture was wrong, and the proxies actually lived in the `conduit` namespace pods. So that's why I restarted the Conduit pods in step 2.

But again, I was surprised and confused to observe that the connection count had not dropped after restarting the Conduit pods.

That's why I ended up using brute force and switching the replica set to another primary node.

**Comment by bourquep** [comment]
When I said _I uninjected Conduit from all services_, it was a bit of a lie 😇. 

I had left Conduit injected into some legacy, very-low-traffic services which I did not think might be involved in all those Mongo connections.

As you can see on the above connection chart, the number of connections to the new primary Mongo node had started climbing above its usual level, and it was still climbing after a while.

So I ended up uninjecting Conduit from all remaining services (really "all" this time), one by one, until there was only one left and the connection count was still climbing.

Shortly after uninjecting Conduit from that single remaining deployment, connection count dropped to its usual level and has been stable since then.

That particular deployment is our legacy API service, which is barely ever hit. I keep it live just so that our users who are on an older version of our client app can still access their data, but there are very few of these users.

It runs an "old" Docker image that hasn't been updated for about a year, so it uses "old" versions of the Mongo driver for NodeJS which may exhibit a connection behavior that is a bit different from latest versions, and that behavior combined to Conduit proxying might lead to the ever-rising connection count.

I'll reinject Conduit in some non-legacy services and observe the Mongo connection count over time, to confirm this hypothesis.

**Comment by bourquep** [comment]
I have injected Conduit into 3 deployments which connect to Mongo, at 10 minute intervals:

1. gRPC service implemented in C# (dotnet core) and uses the `MongoDB.Driver` official Nuget package.
2. `parse-server` [version 2.3.7](https://github.com/parse-community/parse-server/tree/2.3.7) (NodeJS)
3. NodeJS service using the `mongodb` official npm package version 2.2.25

After injecting into 1 and 2, Mongo connection count was stable
After injecting into 3, Mongo connection count started to rise.

It might have something to do with how we initialize the Mongo client object in our NodeJS service, which is behaving properly without Conduit proxy, but causing new connections to build up when going through Conduit.

It is _probably not_ related to the NodeJS Mongo driver, since service 2 is `parse-server`, which is a NodeJS app using the NodeJS driver, does not exhibit the connection count endless growth issue.

I'll add `--skip-outbound-ports mongo_port` when injecting Conduit into service 3 and observe what happens.

**Comment by bourquep** [comment]
So far so good. I have reinjected Conduit into all my prod services with `--skip-outbound-ports` to skip the Mongo db port, and the number of connections to Mongo is stable. Everything else humming smoothly.

I won't have time in the short term to investigate why my NodeJS server keeps creating new Mongo connections when going through the Conduit proxy, but I suppose this is a bug you will want to look into and if it is, I'll be happy to reinject without skipping Mongo in order to analyse logs in more details to see why this may happening

**Comment by wmorgan** [comment]
Thank you for this very detailed description!

**Comment by seanmonstar** [comment]
I believe I have found the reason behind this: our TCP proxy logic receives an incoming TCP stream, creates an outgoing one, and pipes the reads and writes to both of them. However, I think the current thing that does this, being a `copy(in).join(copy(out)`, means that the `out` connection isn't dropped until both sides have shutdown. The inbound closes its connection, but the server never does, so we just sit there waiting for the second future to finish, which never does (or does a loooonngg time in the future).

**Comment by seanmonstar** [comment]
I believe the fix here is probably to change our `join` to a `select`, meaning that if either side hangs up, it's time to shutdown the pipe.

Trying to figure out *a way to test this* is kind of tricky. It feels like it could be done in `proxy/tests/transparency.rs`, by adding a shared counter to our support tcp server to count current connections, but it is flaky in that it depends on timing for the server to notice the new connection, and the proxy to notice the client having closed...

---

@hawkw would you be interested in working on this? If so, I can mentor :)

**Comment by bourquep** [comment]
I've been running 0.3.1 in prod for about an hour, without skipping outbound port 27017 (i.e. connecting to Mongo via Conduit proxy) and so far the number of Mongo connections has been steady. 👏
