### ISSUE TITLE
Conditionally ignore timing-reliant proxy unit tests on CI

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#440]
Right now, there are a handful of proxy unit tests that are annotated with `#[ignore]`, as they rely on timing and may be flaky on CI.  The `#[ignore]` annotation means they will _always_ be skipped. We should change this so that the tests are run locally, but skipped on CI --- possibly by using `#[cfg_attr(...)]` and a feature that's only passed on Travis?

**Comment by briansmith** [comment]
We need to create a mock timer and use the mock timer in the tests so that there are no timing-dependent tests in CI. In particular, the tests for these kinds of things definitely shouldn't be *skipped* in CI.

/cc @olix0r

**Comment by olix0r** [comment]
See https://github.com/tokio-rs/tokio/issues/127

**Comment by briansmith** [comment]
From reading that, it seems like it is going to be a while before Tokio implements anything that will help us with our testing needs.

Although parameterizing every timer over a timer trait might not be appropriate for the lower level libraries like Tokio, can't we parameterize *Conduit*'s fairly limited use of timers and build the mock timer in Conduit's test framework for now?

**Comment by hawkw** [comment]
@briansmith A lot of our current code for timers in the proxy are due to be rewritten soon (#412), so --- while I agree we ought to write our own mock timer --- I think we ought to go ahead with #441 _for now_ (especially since it's blocking the testing of other PRs like #436), as writing a mock timer will require more time and is probably not worth doing until our timeout code is slightly more stable.
