### ISSUE TITLE
Use Prometheus's default histogram sizes

### ISSUE THREAD

**Issue by olix0r** [runconduit/conduit#446]
We've chosen histogram bucket sizes basically off-the-hip. Instead, we should adopt the defaults used by Prometheus's Go library, which are well-tested production defaults used at Soundcloud.

**Comment by adleong** [comment]
Blocked on #425

**Comment by olix0r** [comment]
Cool, so it sounds like we can close this, @siggy?

**Comment by siggy** [comment]
Closing this issue as resolved, let's go with what's defined in the comment above:
https://github.com/runconduit/conduit/issues/446#issuecomment-370605969
