### ISSUE TITLE
Provide helm support for injecting services

### ISSUE THREAD

**Issue by robdefeo** [runconduit/conduit#453]
Currently helm users will install a service via `helm install` or `helm upgrade` this does not work well with `conduit inject`. As I helm user I want to be able to inject conduit services via the helm chart. A sample helm chart to demo how this works would be useful too :) #452

**Comment by briansmith** [comment]
There are probably two parts to this: Supporting Kubernetes 1.9+ using automatic (within-cluster) injection, and supporting earlier versions of Kubernetes somehow.

What versions of Kubernetes are the people who want to try Helm and Conduit together using?

**Comment by robdefeo** [comment]
I took a closer look at `conduit inject` and it works well, the limitations would be around templating and being able to remove a deployment. 

I can upgrade and use 1.9 for this feature, better to support it in the best way rather than trying to be overly backwards compatible

**Comment by wmorgan** [comment]
Let's prioritize 1.9 for Helm support. If we find hordes of people for whom Helm on 1.8 is critical, we can reassess.

**Comment by robdefeo** [comment]
@wmorgan Agreed and the adoption trend will always be 1.9+

**Comment by kfox1111** [comment]
-1. Integration should not be at the helm level at all. I prefer to use helm for everything, but not everything uses helm.

I think an external admission controller for k8s is the right way to do this. conduit can get the yaml as it comes into k8s from tiller or any other uploader and it can be tweaked by conduit on the way into k8s.

**Comment by briansmith** [comment]
> I think an external admission controller for k8s is the right way to do this. conduit can get the yaml as it comes into k8s from tiller or any other uploader and it can be tweaked by conduit on the way into k8s.

This issue is about Helm specifically, but we're currently expecting to solve it more-or-less as you describe here, at least for k8s 1.9+.

**Comment by wmorgan** [comment]
We're tracking admission controller design with #561.

**Comment by wmorgan** [comment]
Any objections to closing this issue in favor of #561?
