### ISSUE TITLE
Connection errors should not propagate as request errors

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#491]
When the proxy attempts to send a request to an endpoint to which there is no preexisting connection, it establishes the connection lazily. If this connection fails (for instance, due to a timeout or socket error), then this failure can result in the request failing entirely.

Instead, the proxy should attempt to dispatch the request to another endpoint in the balancer, or even to the same endpoint if there is only one endpoint in consideration.  The request should be failed only if there are no endpoints in the balancer or if the bind timeout has expired.

---

An issue currently exists in the proxy where a `Timeout` middleware wrapped in a `Reconnect` middleware (from `tower-reconnect`) can cause a request to be canceled, rather than retrying the connection. This is because `Reconnect` implements **reconnecting** on errors *once the connection is successfully established*, but it intentionally does *not* implement **retrying** the connection when an error occurred *while establishing the connection*.

Since the `Timeout` wraps the connection attempt, the connection timing out produces an error while `Reconnect` is in the `Connecting` state, so the error is propagated rather than retrying the connection.

**Comment by hawkw** [comment]
I've opened issue tower-rs/tower#60 against `tower` to track adding retry functionality to `tower-reconnect`. Until then, however, we should resolve this issue in Conduit.

**Comment by briansmith** [comment]
> When the Conduit proxy attempts resolve endpoints from service discovery, it initiates a connection to each endpoint. If the connection cannot be established initially, no subsequent attempts to reconnect to that endpoint are made.

I know you filed this issue regarding the connections that we proxy. However, what about the reconnect logic for the connection between the proxy and the control plane, which has a different code path? If the first connection fails, then will we never try again?

**Comment by briansmith** [comment]
In particular, I wonder if this is part of the problem in #478 and I wonder if we need to make changes to the proxy to fully resolve #478, such as such a fix to the reconnect logic.

**Comment by olix0r** [comment]
@briansmith my initial description of this problem is incorrect, fixing it now

**Comment by olix0r** [comment]
@briansmith Now that I've reviewed the implementation, I believe that we should fail the individual request in this situation, but subsequent requests should trigger a reconnect.

**Comment by seanmonstar** [comment]
I don't believe this affects the controller connection, in fact, there is a unit test that ensures it reconnects.
