### ISSUE TITLE
Update Prometheus config to scrape control-plane pods

### ISSUE THREAD

**Issue by adleong** [runconduit/conduit#501]
Update Conduit's Prometheus config to scrape from all pods with the `conduit.io/control-plane-component` label.

This gives us data about the health of the control plane itself by scraping the metrics from the control plane's proxy sidecars.

These metrics should be labeled so that they are distinguishable from data-plane metrics and should not appear in queries about the data-plane.

**Comment by adleong** [comment]
Blocked on either #425 (for real data) or #498 (for fake data)

**Comment by siggy** [comment]
Fixed as part of #583.
