### ISSUE TITLE
Support Openshift Origin

### ISSUE THREAD

**Issue by xiaods** [runconduit/conduit#52]
origin is k8s enterprise version, we should support it.

**Comment by briansmith** [comment]
> origin is k8s enterprise version, we should support it.

What doesn't work currently?

**Comment by xiaods** [comment]
use cluster-admin to run 
``` conduit install | oc apply -f -```

when it done. i run conduit dashboard, it open the browser, it report wrong:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"web\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**Comment by xiaods** [comment]
sorry, it blocks by china GFW for gcr.io.
