### ISSUE TITLE
Scratch containers can't write to /tmp

### ISSUE THREAD

**Issue by klingerf** [runconduit/conduit#522]
I've been testing @dadjeibaah's changes from #510, and it appears that the 30-second restart issue described in #478 is fixed with his change. It's still the case that in my test environment (minikube) the `destination` service restarts once, immediately, before properly intializing. Here's an example of that the from the `kubectl describe` output:

```
  destination:
    ...
    State:          Running
      Started:      Tue, 06 Mar 2018 16:46:59 -0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 06 Mar 2018 16:46:57 -0800
      Finished:     Tue, 06 Mar 2018 16:46:57 -0800
    Ready:          True
    Restart Count:  1
```

From the failed container's logs:

```
time="2018-03-07T00:46:57Z" level=info msg="running conduit version dev-7c54b70e-kl"
E0307 00:46:57.893390       1 reflector.go:205] github.com/runconduit/conduit/controller/k8s/endpoints.go:145: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0307 00:46:57.893390       1 reflector.go:205] github.com/runconduit/conduit/controller/k8s/endpoints.go:145: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
log: exiting because of error: log: cannot create log: open /tmp/destination.controller-9c7995dc5-v7s8m.unknownuser.log.ERROR.20180307-004657.1: no such file or directory
```

That error actually comes from the glog package, [here](https://github.com/golang/glog/blob/master/glog_file.go#L123), and (I think) the issue is that glog defaults to writing to `/tmp`, and our controllers no longer have a `/tmp` dir now that we switched to the `scratch` base image in #368.

We can override the glog log file directory by adding `-log_dir=/` when starting all of the controller components. Alternatively, we might want to consider adding a `RUN mkdir -p /tmp` line to the Dockerfile that produces the final image. I've verified that setting the `-log_dir` flag fixes the issue, but have not verified the Dockerfile fix.

**Comment by olix0r** [comment]
I suspect that we're best off configuring glog to not use a tmpdir, if that's an option.

AIUI, we'd eventually like to be able to run these containers on a read-only filesystem -- from the security point of view, if there's nothing about the application that requires write access to the filesystem, locking this down may make it harder for an attacker to add executables to the container at runtime.

**Comment by briansmith** [comment]
I agree with @olix0r. We shouldn't be writing to the filesystem in these containers. I filed #523 to enforce this (and other similar things) with a pod security policy.

**Comment by klingerf** [comment]
@olix0r Good point. In that case, instead of setting glog's `-log_dir` flag, we can instead use the `-logtostderr` flag:

```
  -logtostderr
    	log to standard error instead of files
```

Will put together a PR. It's unfortunately that we'll have to set the flag on every command line invocation, since, afaict there isn't a way to change glog's behavior without the use of flags.
