### ISSUE TITLE
Disable push telemetry

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#544]
Until we remove the push-based telemetry ingestion, it might be worthwhile to add a config option allowing it to be conditionally disabled. If the control plane is configured to pull metrics from the prometheus scraping endpoint, it could disable push telemetry so that the proxy logs don't constantly scream about not being able to connect.

---

_Edit_: We're not going to maintain a middle state. We just need to disable push telemetry.

**Comment by olix0r** [comment]
We may not need this, since it's exclusively for an interim state.

**Comment by olix0r** [comment]
waiting on the read-side to be moved over before #616 can resolve this

**Comment by klingerf** [comment]
Fixed by #616.
