### ISSUE TITLE
bin/docker-build should only build the CLI executable for the host platform by default

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#546]
The objective here is to speed up and simplify the edit-build-test cycle by removing inefficiency in how the CLI executable is built, while still being able to reply on `bin/docker-build` to ensure that the CLI executable is built with the same version tag as the rest of Conduit.

Currently:

1. `bin/docker-build` executes `bin/docker-build-cli` (and other things, not relevant to this issue).
2. `bin/docker-build-cli` executes `bin/docker-build-cli-bin`
3. `bin/docker-build-cli` then does the following things:
    1. 3 executables, one for each target platform, are built in a Docker container:
        ```
        RUN CGO_ENABLED=0 GOOS=darwin  go build -o /out/conduit-darwin [...]
        RUN CGO_ENABLED=0 GOOS=linux   go build -o /out/conduit-linux [...]
        RUN CGO_ENABLED=0 GOOS=windows go build -o /out/conduit-windows [...]
        ```
    2. A new Docker container is built, containing just those three output files.
    3. All three executables are extracted out of the Docker image created in step 3.2 into the local filesystem at `target/cli/${os}/conduit`.

In typical usage of `bin/docker-build`, we have almost zero use for anything except the CLI executable for the host platform. That is, if I'm running `bin/docker-build` on Linux in my edit-build-test cycle then I don't care about any of the docker images created above; as far as the `conduit` executable is concerned, I only care that `conduit` is built and written to `target/cli/linux/conduit`. In particular, I never need the conduit images to be built for Windows or Mac. Similarly, somebody running on a Mac doesn't usually need the images built for Linux or Windows.

We should redo this so that the default action of bin/docker-build is to skip as much of the above as possible and directly build `target/cli/${os}/conduit` where `${os}` is the host OS, and only build the other things (the docker images and the executables for other platforms) if/when specifically requested.

**Comment by alenkacz** [comment]
I'll take this one. But my 3 week long vacation start tomorrow so it might take a while... :)

**Comment by wmorgan** [comment]
@alenkacz what better way to spend vacation than by working on Conduit! 😄

**Comment by briansmith** [comment]
@alenkacz Great! Note that I already removed docker-build-cli, so steps 1 and 2 above are now:

> 1. bin/docker-build executes bin/docker-build-cli-bin

**Comment by alenkacz** [comment]
@briansmith yep, I already figured, thanks :)
