### ISSUE TITLE
proxy is slow to shutdown

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#549]
I noticed that once the Conduit control plane is running, if I attempt to delete it with `kubectl delete all --all -n conduit` then the pods stay in the `Terminating` state for a long time: close to 1 minute as reported by `kubectl get all --all`. It takes about 30 seconds for the first container to exit the `Ready` state (as reported by `kubectl get all --all`).

How long it takes to delete the Conduit control plane isn't a major deal. However, it is inconvenient during testing to wait ~1 minute to reset the cluster. Also, this might be indicative of trouble with rolling the control plane.

---

We believe that the proxy prevents pods from shutting down quickly. We need to investigate why that is.

**Comment by briansmith** [comment]
I repeated the measurements above a few times (on an i9-7960x system) in minikube and it's consistently about 50 seconds before the pods go away.

**Comment by olix0r** [comment]
I've also noticed this, but I always assumed this is more about minikube than Conduit.

I don't think this is high-priority before 0.3.1.

**Comment by klingerf** [comment]
@briansmith Your system is clearly faster than mine :)

I tested this, and it appears that delete times are basically unchanged as a result of #510.

Current master:

```bash
$ conduit version
Client version: git-83d6a1f5
Server version: git-83d6a1f5

$ kubectl delete all --all -n conduit > /dev/null && time while true; do if [ $(kubectl -n conduit get po 2> /dev/null | wc -l) -eq 0 ]; then break; fi; sleep 0.2; done

real	1m14.211s
```

Compared to 72c6a9c:

```bash
$ conduit version
Client version: git-72c6a9ca
Server version: git-72c6a9ca

$ kubectl delete all --all -n conduit > /dev/null && time while true; do if [ $(kubectl -n conduit get po 2> /dev/null | wc -l) -eq 0 ]; then break; fi; sleep 0.2; done

real	1m7.328s
```

**Comment by klingerf** [comment]
Out of curiosity I rolled back to the commit immediately before #365, when we started injecting the proxy into the control plane when installing conduit, and delete times are _much_ faster.

```bash
$ conduit version
Client version: git-7365c564
Server version: git-7365c564

$ kubectl delete all --all -n conduit > /dev/null && time while true; do if [ $(kubectl -n conduit get po 2> /dev/null | wc -l) -eq 0 ]; then break; fi; sleep 0.2; done

real  0m6.397s
```

When I roll forward one commit to f66ec64, I get:

```bash
$ conduit version
Client version: git-f66ec641
Server version: git-f66ec641

$ kubectl delete all --all -n conduit > /dev/null && time while true; do if [ $(kubectl -n conduit get po 2> /dev/null | wc -l) -eq 0 ]; then break; fi; sleep 0.2; done

real  1m4.186s
```

This makes me think that the delete delay stems from shutting down the proxy. It also means that the controller shutdown time is a regression from the v0.3.0 release. If we're concerned about that we should consider removing the proxy from the control plane prior to release.

**Comment by briansmith** [comment]
@klingerf Thanks for doing that. I was just about to do the same investigation!

If the problem is caused by the proxy, then it's likely actually a more serious problem because it potentially causes this problem for any/every pod that it gets injected into. We have a an issue #430 targeted for 0.4.0 to address graceful proxy shutdown.

Maybe we should check termination time of pods that have the project injected into them, for the current master vs. 0.3.0 vs. 0.2.0 and see if we regressed anything in the 0.3.1 and/or 0.3.0 release.

**Comment by klingerf** [comment]
Ok, have tested this against the [hello world app from the linkerd-examples repo](https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/hello-world.yml).

When the app is uninjected, the delete time is low:

```
$ kubectl delete -f hello-world.yml > /dev/null && time while true; do if [ $(kubectl get po 2> /dev/null | wc -l) -eq 0 ]; then break; fi; sleep 0.2; done

real	0m6.554s
```

Whereas when it's injected with the latest master (83d6a1f5) it's slow:

```
$ kubectl delete -f hello-world.yml > /dev/null && time while true; do if [ $(kubectl get po 2> /dev/null | wc -l) -eq 0 ]; then break; fi; sleep 0.2; done

real	1m36.994s
```

And it's similar for the same application injected with conduit v0.3.0:

```
$ kubectl delete -f hello-world.yml > /dev/null && time while true; do if [ $(kubectl get po 2> /dev/null | wc -l) -eq 0 ]; then break; fi; sleep 0.2; done

real	1m32.394s
```

So this doesn't appear to be a regression since v0.3.0 (although it is a regression for the controller shutdown time specifically). I think we should just prioritize fixing #430.

**Comment by briansmith** [comment]
I also see the same issue for some non-control-plane pods in my testing.

**Comment by briansmith** [comment]
Based on all the comments above, I'm taking this out of the 0.3.1 milestone. However, it is *extremely* annoying for development purposes and IMO it needs to be fixed right away, so I'm speculatively setting it as 0.4.0 P0.

**Comment by olix0r** [comment]
I think we should handle `TERM` and `QUIT`.

I think it's higher priority to shutdown quickly, and we should prioritize graceful draining as a followup.

**Comment by briansmith** [comment]
> Next, I wondered if it had to do with the proxy being in a Docker container, and apparently it is. Docker by default makes the contained process PID 1, which is special and has no default signal handlers. Soooo, we can add some into the proxy directly.

We should not be running the proxy as PID 1. If we run the proxy under a different PID then does that simplify the shape of the fix? If so, we should do that first.

**Comment by seanmonstar** [comment]
In the articles I read, I saw mention of [tini](https://github.com/krallin/tini) and [dumb-init](https://github.com/Yelp/dumb-init).

Assuming something else acts as a better PID 1, that should mean the proxy has its default signal handlers again, and it would close when getting SIGTERM.

**Comment by briansmith** [comment]
I recommend we all read https://www.ianlewis.org/en/almighty-pause-container. Basically, we can't assume that we're running as PID 1 and we can't assume that we're not running as PID 1 because the PID configuration and whether or not the pause container is used depends on the pod configuration, which we have to let the user control, and the user might choose different settings for different pods.

My understanding is that upon SIGTERM we're planning to do something beyond exiting immediately, e.g. drain request queues and/or wrap up telemetry or something. Therefore, it seems inevitable that we're going to have a SIGTERM handler. And if that's the case then we might as well add one now since that will make us work consistently whether we're PID 1 or not. Does everybody agree with that?

**Comment by olix0r** [comment]
@briansmith per https://github.com/runconduit/conduit/pull/581#issuecomment-373843112 i was definitely wrong about `SIGQUIT`.

I'm in agreement with that: I think we should definitely handle SIGTERM, and I think we should handle SIGINT for the sake of consistency with other Conduit components.
