### ISSUE TITLE
Regression: Proxy ignores Host header when deciding whether to use the Destination service to resolve a name

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#552]
@klingerf traced this regression to 569d6939a799bb0df6bd4053de7d7e8ac6b49ab6 (https://github.com/runconduit/conduit/pull/492). I also independently bisected the regression to that revision.

This code in the `Recognize` implementation of `Outbound` only considers the authority part of the Request URI, and doesn't consider the Host header field value: https://github.com/runconduit/conduit/blob/9cdc485ee42e5d7175f2336b695797c2d4d315ff/proxy/src/outbound.rs#L90-L95

As a consequence, the proxy ignores the `Host` header field when deciding whether to route the resolve the authority with the Destination service or to fall back to SO_ORIGINAL_DST.

It seems like we're expecting `normalize_our_view_of_uri()` to have been called and to have set the authority in the request URI before this code is executed, but that hasn't happened.

I also noticed that it seems wrong that we execute the SO_ORIGINAL_DST logic in two different places. 
In one instance, the `Recognize` implementation for `Outbound` uses SO_ORIGINAL_DST, here: https://github.com/runconduit/conduit/blob/9cdc485ee42e5d7175f2336b695797c2d4d315ff/proxy/src/outbound.rs#L110-L115

That implies that `recognize()` does NOT expect `normalize_our_view_of_uri()` to have been called beforehand. Yet, this contradicts the logic quoted earlier from the same function, which seems to assume that `normalize_our_view_of_uri()` *has* been called. If `normalize_our_view_of_uri()` already been called then it would have already set the authority to the SO_ORIGINAL_DST so we wouldn't need to query it again; see the code in `normalize_our_view_of_uri()`: https://github.com/runconduit/conduit/blob/9cdc485ee42e5d7175f2336b695797c2d4d315ff/proxy/src/transparency/h1.rs#L32-L44

The consequence of this is that we now have the opposite problem of #155: The destination service is never used for any service, so we've effectively disabled load balancing, but now every external (and internal) service is reachable. This is why #155 appears to be fixed; as soon as *this* issue is fixed, #155 will be broken again.

**Comment by briansmith** [comment]
In particular, in my testing of a request to `http://httpbin.org/anything` at the point we execute this code:
 https://github.com/runconduit/conduit/blob/9cdc485ee42e5d7175f2336b695797c2d4d315ff/proxy/src/outbound.rs#L90-L95:

`req.uri()` will be '/anything` and so `req.uri().authoriity_part() == None`. Consequently, `local == None` at this point:
https://github.com/runconduit/conduit/blob/9cdc485ee42e5d7175f2336b695797c2d4d315ff/proxy/src/outbound.rs#L104-L108.
Consequently, we won't use the Destination service.

**Comment by seanmonstar** [comment]
I'm at a conference today, so my time is spotty. To start with a test, I'd add a new case in destination.rs, that sets up the controller to point at an h1 server, but skip setting it as the outbound property (in the test code, that sets mocked original dst), and start debugging from there.

**Comment by olix0r** [comment]
As part of the fix for this, I think we need to write a user-facing doc describing how a request is routed. It's become complicated enough that I couldn't easily explain it off the top of my head.

**Comment by hawkw** [comment]
Okay, I think I have some inkling of what's going on here and will look into fixing it today. Thanks for the detailed report, @briansmith!

**Comment by seanmonstar** [comment]
I put together this unit test that shows the proxy is creating a "not recognized" error: https://github.com/runconduit/conduit/compare/discovery-http1-unit-test

**Comment by hawkw** [comment]
Thanks @seanmonstar, that was the first thing I was going to do, too.

**Comment by briansmith** [comment]
> As part of the fix for this, I think we need to write a user-facing doc describing how a request is routed. It's become complicated enough that I couldn't easily explain it off the top of my head.

I don't think we should block 0.3.1 on writing a user-facing document. It's more time-consuming to write a user-facing doc than it initially appears, which is why #421 isn't complete yet. Also, what we currently do and what we'll do in 0.4.0 (or so) will be different, so it would be a waste to write it now.

For 0.3.1 we need to make sure that the PR author and reviewer truly understand the code. We can then write up the documentation post-0.3.1. We should also have a discussion about what we can do to simplify this code to make it clearly correct, after 0.3.1.

**Comment by hawkw** [comment]
Okay, I have a fix for the issue here. Will push it up in a moment. I'm talking with @olix0r about improving the documentation as well.
