### ISSUE TITLE
The Destination service should notify the proxy when the service doesn't exist

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#563]
See #155. The proxy needs to know when the service doesn't exist (independently of whether it has any endpoints available) so that it can decide whether to fall back to DNS. A PR to document the syntax and semantics of the gRPC API change between the proxy and the destinations service will be provided shortly.

**Comment by briansmith** [comment]
#564 adds the proposed API and the proxy-side changes. The Go code for the API needs to be regenerated in that PR, so that PR currently breaks the build.

**Comment by klingerf** [comment]
@briansmith Ok, sounds good. I will base my branch for this issue off of `b/dns-fallback-destination-api-change` if that works for you.

**Comment by briansmith** [comment]
Yes that would be great.

**Comment by klingerf** [comment]
Fixed by #568.
