### ISSUE TITLE
Implement request duration metric in the proxy

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#570]
PR #536 describes a `request_duration_ms` metric reported by the proxy. We are currently not able to collect this metric, as the proxy's `sensors` do not generate events for the end of a request stream. 

We could generate these events by instrumenting request bodies the same way we instrument response bodies, which I've started on in [this branch](https://github.com/runconduit/conduit/tree/eliza/request-duration-metrics); however, getting it to compile will require updating a lot of type bounds pretty much everywhere else in the proxy.

**Comment by adleong** [comment]
This will also unblock changing the `request_total` counter from being incremented when the request stream is initiated to being incremented when the request stream is completed.  This is desirable for consistency with the `response_total` counter which is incremented when the response stream is completed.

**Comment by hawkw** [comment]
Update: finally squished out all the type errors, so the proxy compiles with the addition of stream end events now. Will need to do some additional work to actually consume those events in metrics, but that's the easy part.
