### ISSUE TITLE
Destination service does not watch for changes to ExternalName-type services

### ISSUE THREAD

**Issue by klingerf** [runconduit/conduit#571]
When adding support to the destination service for resolving ExternalName-type services in #490, I overlooked the need to update the subscriber if the external name is changed or the service is deleted. We need to add a service watch that does this, similar to what already exists for non-ExternalName-type services in endpoints.go.

**Comment by briansmith** [comment]
After the code for doing DNS lookups in the controller Destination service was written, when testing it, we found the k8s documentation that said that ExternalName services are published in DNS as `CNAME` entries. That means that after #155 is fixed, we can probably treat `ExternalName` services just like other kinds of external services, and have the proxies do the DNS. The proxy's polling of DNS would allow it to automatically discover any changes of the sort that are indicated as being problematic here, AFAICT. Such a change would also result in our DNS logic having a very high fidelity with respect to node- and/or pod- specific DNS configuration. And it would eliminate the duplication of DNS logic.

**Comment by klingerf** [comment]
The fix for this is reviewable in #764.

**Comment by briansmith** [comment]
Resolved by #764.
