### ISSUE TITLE
cli/Dockerfile hard-codes `latest` tag for its gcr.io/runconduit/cli-bin base image (`gcr.io/runconduit/cli-bin:latest`)

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#578]
```docker
FROM gcr.io/runconduit/cli-bin:latest as build
```

The tag shouldn't be `latest`; it should be whatever tag we used for building cli-bin.

**Comment by olix0r** [comment]
I'm not sure if the `cli` image is used at all. We might opt to kill it off until it's needed.
