### ISSUE TITLE
Use a port range for simulate-proxy's metric-addr flag

### ISSUE THREAD

**Issue by dadjeibaah** [runconduit/conduit#595]
This is a follow up issue based on PR #576. Based on this PR, the simulate-proxy process allows a user to provide a set of endpoints to use for prometheus metrics. The `metric-addrs` flag requires a comma separated list of strings in the form of `:9000,:9001,:9002`. It would be better to have this list be in the form of `9000-9002` which is more concise and would make adding a large number of port ranges (e.g. `1234-10000`) much easier.

**Comment by klingerf** [comment]
This appears to be done, closing.

```
  -metric-ports string
    	range (inclusive) of network ports to serve prometheus metrics (default "10000-10002")
```
