### ISSUE TITLE
Proxy /metrics endpoint should support GZIP compression

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#598]
According to [the Prometheus documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#format-version-0-0-4), metrics export endpoints should support an optional `Content-Encoding: gzip` header. Since there's some concern about the wire size of metrics reports (_viz._ https://github.com/runconduit/conduit/pull/536#discussion_r175645811), we should look into adding support for compression.

**Comment by briansmith** [comment]
According to that discussion, "1046 lines per service that this instance communicates with. Each line is around 100 characters long so roughly in the neighborhood of 100kb per service before any type of compression." How often does Prometheus poll each pod?

If the size of the data is actually 100kb per service that is contacted, then does that mean we're storing ~100kb per service of data in memory for metrics? Do we send the response with HTTP/1.1 chunked encoding or do we buffer it in memory to calculate the Content-Length? Can we reduce the raw size of the data substantially (e.g. to 1/2 or 1/10th its current size, or more) to reduce the memory used for it? If so, I think it would be good to reduce the uncompressed size and then reconsider how useful the compression would be.

**Comment by hawkw** [comment]
@briansmith 
> How often does Prometheus poll each pod?

I believe the default is every ten seconds; this is configurable.

> If the size of the data is actually 100kb per service that is contacted, then does that mean we're storing ~100kb per service of data in memory for metrics?

Almost certainly not; a majority of this data is due to the very repetitive nature of the Prometheus text format. Consider, for example, a latency histogram stat, whose textual representation is something like
```
# HELP response_latency_ms A histogram of the total latency of a response. This is measured from when the request headers are received to when the response stream has completed.
# TYPE response_latency_ms histogram
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="1"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="2"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="3"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="4"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="5"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="10"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="20"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="30"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="40"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="50"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="100"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="200"} 1
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="300"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="400"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="500"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="1000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="2000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="3000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="4000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="5000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="10000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="20000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="30000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="40000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="50000"} 0
response_latency_ms{authority="localhost:4140",status_code="404",direction="outbound",le="+Inf"} 0
response_latency_ms_count{authority="localhost:4140",status_code="404",direction="outbound"} 0
response_latency_ms_sum{authority="localhost:4140",status_code="404",direction="outbound"} 0
```
That string is 2,951 characters long --- nearly 3kb. Meanwhile, the in-memory representation of that stat is basically just the string `"localhost:4140"` (14 bytes), the `u16` `404`, an array of 51 `u32`s, and a `u64` --  about 230 bytes. Even with the added overhead of a few pointers, the in-memory representation of the stat is an order of magnitude smaller than the textual representation. 

Furthermore, the repetitiveness of the text format means that we're likely to see some pretty significant impact from compression.

**Comment by briansmith** [comment]
Seeing that, I agree that `Content-encoding: deflate` (with `Transfer-encoding: chunked`) seems like a good solution. (I don't think we should give the labels less clear names just to reduce their size, if anybody might actually use the data directly.)

**Comment by hawkw** [comment]
> I don't think we should give the labels less clear names just to reduce their size, if anybody might actually use the data directly.

I strongly agree!
