### ISSUE TITLE
Destination service doesn't send a heartbeat message as documented

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#610]
@klingerf noticed that the proto file for the Destination API says:

```proto
// ... The controller is also expected to send an
// update at least once every ADDRESS_UPDATE_INTERVAL to indicate that the
// controller is still healthy.  If no service discovery updates have taken
// place, the controller can simply send an empty `add`.  The controller may
// determine the value of ADDRESS_UPDATE_INTERVAL.
```

1. This doesn't seem to be implemented at all.
2. It seems like, if we were to implement it, an empty `add` message would be potentially wrong in the case where there are no endpoints (a `no_endpoints` message was received) and the service does not exist.
3. AFAICT we don't really need a heartbeat message like this per-service-per-proxy-instance, but rather just per-proxy-instance.

@adleong, @klingerf Do you have any thoughts about this? I'm tempted to just remove this part of the documentation.

**Comment by adleong** [comment]
I'm okay with removing this.  We can revisit in the future if we think this would be useful.

**Comment by klingerf** [comment]
Removing the comment works for me too.
