### ISSUE TITLE
support kubernetes initializer

### ISSUE THREAD

**Issue by xiaods** [runconduit/conduit#636]
see initializer example for envoy: https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/master/docs/deploy-envoy-initializer.md

so i think conduit also can support it like this deployment:
https://raw.githubusercontent.com/kelseyhightower/kubernetes-initializer-tutorial/master/deployments/helloworld-with-annotation.yaml

**Comment by olix0r** [comment]
thanks @xiaods.  As i understand it, kubernetes is deprecating initializers in favor of Admission Controllers. we're currently pursuing an admission controller based solution in https://github.com/runconduit/conduit/issues/561. I think @rmars had a small prototype working last week, but i expect us to make more progress on this after the 0.4.0 release.
