### ISSUE TITLE
Destinations service keeps complaining about external name not being valid IP

### ISSUE THREAD

**Issue by pcalcado** [runconduit/conduit#643]
When resolving an [`ExternalName` service](https://kubernetes.io/docs/concepts/services-networking/service/), the IP is resolved but the logs complain about the IP.

## Reproducing

Env:

```shell
pcalcado@arbeitsziege.local$ git rev-parse HEAD
1ed4a93b5ecf68ceb758c7f375e9eb528c689849
pcalcado@arbeitsziege.local$ go version
go version go1.10 darwin/amd64
pcalcado@arbeitsziege.local$ minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100
pcalcado@arbeitsziege.local$ minikube version
minikube version: v0.25.0
pcalcado@arbeitsziege.local$  kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

1. Run destination service locally using something like ` $ ./bin/go-run controller/cmd/destination -kubeconfig ~/.kube/config -log-level debug`
2. Deploy an ExternalName service like below:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: test-service
  namespace: default
spec:
  type: ExternalName
  externalName: conduit.io
```
3. Run the client script like this: `$  bin/go-run  controller/script/destination-client/main.go -path  test-service.default.svc:80 -addr :8089`

#### What happens:
The client receives the correct IP:
```
INFO[0000] Add:
INFO[0000] - 104.24.100.143:80
INFO[0000] - 104.24.101.143:80
INFO[0000]
```

But this message is displayed in the destination services log:
```
...
INFO[0001] [endpoints watcher] initialized
INFO[0001] [endpoints watcher] initialized
INFO[0001] Adding ipv4 name resolver
INFO[0001] Adding k8s name resolver
INFO[0001] starting gRPC server on 127.0.0.1:8089
INFO[0001] serving scrapable metrics on :9999
DEBU[0007] Get scheme:"k8s" path:"stat-test-t2-svc.conduit-stat-test.svc.cluster.local:80"
INFO[0007] Establishing watch on endpoint conduit-stat-test/stat-test-t2-svc:80
DEBU[0082] Updating conduit-stat-test/stat-test-t2-svc:80 to [172.17.0.22:80,172.17.0.41:80,172.17.0.42:80,172.17.0.43:80,172.17.0.45:80,172.17.0.46:80,172.17.0.47:80,172.17.0.48:80]
DEBU[0082] Updating conduit-stat-test/stat-test-t2-svc:80 to [172.17.0.41:80]
DEBU[0155] Updating conduit-stat-test/stat-test-t2-svc:80 to []
DEBU[0158] Updating conduit-stat-test/stat-test-t2-svc:80 to []
DEBU[0159] Updating conduit-stat-test/stat-test-t2-svc:80 to [172.17.0.22:80]
INFO[0221] Stopping watch on endpoint conduit-stat-test/stat-test-t2-svc:80
DEBU[0245] Get scheme:"k8s" path:"200.1.2.3:80"
DEBU[0267] Get scheme:"k8s" path:"example.org:80"
DEBU[0732] Get scheme:"k8s" path:"test-service.default.svc:80"
INFO[0732] Establishing dns watch on host conduit.io
INFO[0732] 2400:cb00:2048:1::6818:658f is not a valid IP address
INFO[0732] 2400:cb00:2048:1::6818:648f is not a valid IP address
INFO[0742] 2400:cb00:2048:1::6818:658f is not a valid IP address
INFO[0742] 2400:cb00:2048:1::6818:648f is not a valid IP address
INFO[0752] 2400:cb00:2048:1::6818:658f is not a valid IP address
INFO[0752] 2400:cb00:2048:1::6818:648f is not a valid IP address
INFO[0762] 2400:cb00:2048:1::6818:658f is not a valid IP address
```
#### What did I expect to happen
No log message as this is a valid IP.

**Comment by xabxx** [comment]
Heyyy, so I think `2400:cb00:2048:1::6818:648f ` is the IP address that is given to `ParseIPV4`in utils be resolved, and it's not resolvable. It does take the valid ip addr - 104.24.101.143 sometimes and when that happens, it doesn't log anything, which is the expected output.  just FYI , and i am doing more investigation to see who is the culprit щ（ﾟДﾟщ）

**Comment by briansmith** [comment]
`2400:cb00:2048:1::6818:648f` is an IPv6 address.

With respect to this specific issue, we may be able to resolve this by following the course of action suggested at https://github.com/runconduit/conduit/issues/571#issuecomment-379356516: remove the DNS logic from the control plane. We should figure out if that will work before doing significant work here.

However, regardless of that, we should look at any IP address parsing we are doing in our Go code and make sure it is IPv6-capable or at least IPv6-tolerant.

**Comment by xabxx** [comment]
@briansmith will implementing a ipv6 parser in util.go and have dns.go call both(ipv4+6parse) to determine if an ip is valid solve this issue? i.e. will that make it "IPv6-capable or at least IPv6-tolerant" ?

**Comment by xabxx** [comment]
#727

**Comment by briansmith** [comment]
This code was removed in PR #764.
