### ISSUE TITLE
harmonize destination service and metrics labels

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#655]
Followup from https://github.com/runconduit/conduit/pull/654#discussion_r178204978

We should consistently describe Kubernetes objects in our interfaces.

## Prometheus labels

https://github.com/runconduit/conduit/blob/666c83e96374352a68b6155ef7ebc931d244dfa6/doc/proxy-metrics.md specifies:
- `namespace`
- `deployment`
- `pod_name`
- `pod_template_hash`
- `replica_set`
- `replication_controller`
- `daemon_set`
- `k8s_job`

## Destination service

#654 introduces:
- `k8s_namespace`
- `k8s_service`
- `k8s_pod`

## Proposal

- rename `pod_name` to `pod` in prometheus
- drop `k8s_` from destination service
- specify `service` and `dst_service` in `proxy-metrics.md`

**Comment by klingerf** [comment]
Am adding @adleong's comment from #654 here, since I think it should be addressed as part of the work outlined in this issue:

> I don't think we want to send the `k8s_pod` label as this will cause the proxy to expose a `dst_k8s_pod` label which will be of large cardinality.  Instead, I think we should be setting `k8s_job` or `k8s_replicaset` or `k8s_deployment`... etc.  These can be found by using `pod.GetOwnerReferences()`.  See `GetDeploymentForPod` in `replicasets.go` for an example.
