### ISSUE TITLE
TTLs are not honored when DNS is used for service discovery

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#711]
In the proxy, DNS is hard-coded (as of #155) to poll every 5 seconds because the DNS API being used doesn't make TTL information readily available. However, it shouldn't be a terrible amount of work to use a different API to get the TTLs and then poll DNS at the rate indicated by the shortest TTL.

I think there may be a similar issue with the way the controller's Destination service does DNS, but I think that might be resolved by removing DNS code from the controller side of the Destination service; see https://github.com/runconduit/conduit/issues/571#issuecomment-379356516.

One issue with honoring short TTLs is that it would cause us to do many more DNS queries when the TTLs are short. Some clusters, especially ones that do sophisticated load balancing through DNS, might have TTLs of 1ms or similar. That would result in doing a DNS query every millisecond per DNS name per proxy instance. We might want to follow up any work we do here with a "save my laptop's battery" setting that clamps the minimum TTL to some comfortable value.

/cc @olix0r for thoughts.

**Comment by briansmith** [comment]
@bluejekyll is the primary maintainer of trust-dns. Working together, we created trust-dns-resolver to be a lighter-weight library for applications that don't need all the implementation of the trust-dns client. In other words, trust-dns-resolver doesn't depend on trust-dns client and the trust-dns client would be a heavier dependency.

In the case of the TTL functionality we probably "just" need to modify trust-dns-resolver to expose the TTLs; (We also have other changes we'll need to make, e.g. we want to do custom CNAME processing and/or custom DNS `search` processing, so I think we should expect to be contributing to changing trust-dns-resolver over time.) For our current purposes it would be sufficient if `resolve_ip` just returned the shortest deadline of all A/AAAA records and/or any CNAME records in the CNAME chain.

Note also that trust-dns-resolver maintains its own cache of DNS records that we mostly don't really need or want in Conduit, since we do our own higher-level, protocol-independent, caching. If we don't disable the trust-dns-resolver DNS cache then we need to make sure that we requery DNS after the DNS records actually expire. Ideally the deadline that trust-dns-resolver provides for us would guarantee this property.

**Comment by hawkw** [comment]
@briansmith 
> In other words, trust-dns-resolver doesn't depend on trust-dns client and the trust-dns client would be a heavier dependency.

Ah, okay, thanks for clearing that up --- I took the line in [the `trust_dns` docs](https://docs.rs/trust-dns/0.13.0/trust_dns/) "[f]or a system like resolver built on top of the `Client` library, see `trust-dns-resolver`" to mean that `trust-dns-resolver` depended on `Client`.

> In the case of the TTL functionality we probably "just" need to modify trust-dns-resolver to expose the TTLs; 

Okay, that sounds good!

> [...] disable the trust-dns-resolver DNS cache [...]

Do you know off the top of your head if this can be done by setting the [`cache_size` field on `ResolverOpts`](https://docs.rs/trust-dns-resolver/0.8.2/trust_dns_resolver/config/struct.ResolverOpts.html#structfield.cache_size) to 0, or will changes to `trust-dns-resolver` be necessary to allow us to disable caching? If you don't know the answer, I'm happy to take a look at the code, but figured it was worth asking.

**Comment by briansmith** [comment]
> Do you know off the top of your head if this can be done by setting the cache_size field on ResolverOpts to 0, or will changes to trust-dns-resolver be necessary to allow us to disable caching? If you don't know the answer, I'm happy to take a look at the code, but figured it was worth asking.

I don't know. Either way, I would verify for yourself whether trust-dns-resolver works correctly with a cache size of zero, especially w.r.t. CNAME chaining, by inspecting the code and/or writing tests.

**Comment by bluejekyll** [comment]
>  I took the line in the trust_dns docs "[f]or a system like resolver built on top of the Client library, see trust-dns-resolver" to mean that trust-dns-resolver depended on Client.

We should update those docs. The Resolver did in fact depend on Client initially, and then @briansmith and I refactored it as mentioned above. Sorry for the confusion!

As to TTLs, that should be exposed from the `LookupIp` object.

**Comment by hawkw** [comment]
@bluejekyll 
> Sorry for the confusion!

Don't worry about it! :)

> As to TTLs, that can be exposed from the `LookupIp` object (easily I think).

Okay, that's what I thought, thanks for the confirmation! I'll start on a PR.

**Comment by bluejekyll** [comment]
probably adding a TTL field to this: https://github.com/bluejekyll/trust-dns/blob/master/resolver/src/lookup.rs#L36

and then capturing it during construction of the `Lookup`: https://github.com/bluejekyll/trust-dns/blob/master/resolver/src/dns_lru.rs#L66

And you can see the TTL is available directly above line 66.

**Comment by hawkw** [comment]
I've opened bluejekyll/trust-dns#444 to expose the TTLs in the `Lookup` and `LookupIps` APIs.

**Comment by hawkw** [comment]
I've pushed [a branch](https://github.com/runconduit/conduit/compare/eliza/dns-ttls?expand=1) that makes this change. However, it's currently very difficult to write tests for without changes in downstream libraries, so I'm planning on making some downstream changes and holding off on merging until this branch can be tested.
