### ISSUE TITLE
Eliminate cloning in `control::Cache`

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#713]
See https://github.com/runconduit/conduit/pull/688#discussion_r179838359

We should be able to remove the cloning of cache values in the proxy's `control::Cache` module significantly, by moving them out of the maps to update the cache with (as they will no longer be needed), and by changing the way values are associated with cache change events.

**Comment by briansmith** [comment]
I expect that we should be able to *eliminate*, not just *reduce*, the cloning. And maybe we can remove the `V: Clone` bound.
