### ISSUE TITLE
Web sidebar does not extend to the bottom of the page on long pages

### ISSUE THREAD

**Issue by klingerf** [runconduit/conduit#72]
If the page content is long enough (200vh), then the sidebar does not extend to the bottom of the page. It looks like this:

![image](https://user-images.githubusercontent.com/9226/34186680-1831e890-e4e2-11e7-8b9e-e526b185e7d7.png)

**Comment by rmars** [comment]
This causes the "Update now" button to be isolated and look weird:
![screen shot 2018-01-19 at 1 39 47 pm](https://user-images.githubusercontent.com/549258/35172872-3df59280-fd1e-11e7-853d-318253a39878.png)
