### ISSUE TITLE
 destination service must add `daemon_set` labels

### ISSUE THREAD

**Issue by olix0r** [runconduit/conduit#721]
The destination service currently adds the following labels to destinations:

```
namespace="emojivoto",
pod="voting-7f6d846b56-8sqmc",
```

If this pod is in the `ds/voting`, it should also add:
```
daemon_set=voting
```

**Comment by klingerf** [comment]
@briansmith It turns out changing these labels to remove the underscores is a bit more involved, so I'm not going to pursue it as part of #731. Have opened #740 to track making the change separately.
