### ISSUE TITLE
There is no way to change the proxy log level for a pod without re-injecting the proxy

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#756]
When a user reports a problem, we frequently ask them to re-run `conduit inject` on the affected pods using a different proxy log level. This is too much to expect a bug reporter to do in general. With production users, it's likely completely unrealistic. We should find an easier and less disruptive way to change the proxy log level for the pods in a deployment and/or for specific pods.

One possibility (easy): Document (on conduit.io, ideally) how to use `kubectl edit` to change *just* the `CONDUIT_PROXY_LOG` setting to a "full diagnostic" setting (e.g. "CONDUIT_PROXY_LOG=conduit_proxy=trace,hyper=trace,h2=trace,tower_balance=trace`, as suggested to users in previous bug reports).

Another possibility (harder): Have the proxy create an *optional* mount for a configmap. The configmap contains key=value entries, using the `CONDUIT_` environment variable names as keys, and where the values are interpreted the same way as env. vars. The Conduit proxy loads its initial configuration from the environment variables. Then, if configmap map mount exists, a file will exist at the given path; in that case, update any configuration settings according to the values in the configmap. Use `inotify` to watch for changes to that configmap and dynamically change the settings. Not all settings would support such runtime re-configuration, but at least `CONDUIT_PROXY_LOG` would.

**Comment by briansmith** [comment]
On the other hand, I guess the real problem is that the logging we're doing by default is insufficient. Users shouldn't need to change the log level to solve problems. So, any time a user reports an issue and we ask them to increase the logging level, we should figure out which log messages in the more verbose output were useful for diagnosing the issue, and make that information available by default.

**Comment by olix0r** [comment]
@briansmith that's more-or-less my view as well.  logging should be useful to developers, but it's my view that operators should not have to read conduit proxy logs _ever_. If there are cases where there are operator-facing information in logs, we should figure out how to expose this information in the controller (i.e. via API). For developer-facing debugging, we may want a way to collect/snapshot richer diagnostic information on-demand.

**Comment by briansmith** [comment]
I don't agree that users should never look at the proxy log. I'm also not convinced we need our own API for logs (or similar), at least when running in Kubernetes, since Kubernetes already provides an API for getting the logs for a pod container, which is what `kubectl` uses.

However, it seems we do agree that the defaults are *supposed* to be sufficient and that our goal should be to make it so that changing the log level isn't required except in abnormal situations, so I'm closing this.

**Comment by olix0r** [comment]
@briansmith 

> I'm also not convinced we need our own API for logs (or similar), at least when running in Kubernetes, since Kubernetes already provides an API for getting the logs for a pod container

I mean that we should expose APIs/tools to answer the questions you would want to ask of the logs.
