### ISSUE TITLE
conduit dashboard ,routes page blocked script .

### ISSUE THREAD

**Issue by yyydao** [runconduit/conduit#76]
I run 
```
$ conduit dashboard
Running `kubectl proxy --port=8001`
Starting to serve on 127.0.0.1:8001
Opening http://127.0.0.1:8001/api/v1/namespaces/conduit/services/web:http/proxy/ in the default browser
```

and then I visit`http://127.0.0.1:8001/api/v1/namespaces/conduit/services/web:http/proxy/routes`,and get no content in web main area.

And my devtool get these message:
![image](https://user-images.githubusercontent.com/1823279/34196633-eb9099d2-e59d-11e7-8d20-feed5faeb1ad.png)

**Comment by rmars** [comment]
Hi @yyydao thanks for filing this! 
- The `/routes` endpoint currently doesn't serve anything (we should probably better indicate this).
`http://127.0.0.1:8001/api/v1/namespaces/conduit/services/web:http/proxy/servicemesh` and `http://127.0.0.1:8001/api/v1/namespaces/conduit/services/web:http/proxy/deployments` should show data though.
- We're currently working on cleaning up those errors, stay tuned!

**Comment by siggy** [comment]
JavaScript errors should be fixed as part of: https://github.com/runconduit/conduit/pull/79
