### ISSUE TITLE
Add replication controller stats to web UI / grafana

### ISSUE THREAD

**Issue by klingerf** [runconduit/conduit#795]
#794 wires up the public api's `StatSummary` endpoint to start returning replication controller stats. We should surface those stats in the web UI, and link them to a replication-controller-specific grafana dashboard.

This will require changing the public api's `ListPods` endpoint to start returning pod owners that are not deploys. I think something like this would work:

```diff
diff --git a/proto/public/api.proto b/proto/public/api.proto
index 96bb376..2a7f178 100644
--- a/proto/public/api.proto
+++ b/proto/public/api.proto
@@ -22,7 +22,10 @@ message ListPodsResponse {
 message Pod {
   string name = 1;
   string podIP = 2;
-  string deployment = 3;
+  oneof owner {
+    string deployment = 3;
+    string replication_controller = 9;
+  }
   string status = 4;
   bool added = 5; // true if this pod has a proxy sidecar (data plane)
   google.protobuf.Duration sinceLastReport = 6;
```

As part of this change we'll also need to rethink the service mesh overview page in the web UI, which at present is fairly deploy-centric. For instance, if a cluster doesn't have any meshed deployments but it does have meshed replication controllers, then we shouldn't display the call-to-action.

**Comment by rmars** [comment]
#893 moved the ServiceMesh page to be namespace-centric, and changed the messaging around adding resource to the mesh. Going to consider this ticket done.
