### ISSUE TITLE
Secure data plane communication

### ISSUE THREAD

**Issue by adleong** [runconduit/conduit#8]
The Conduit proxy should secure pod to pod communication with TLS.

**Comment by xiaods** [comment]
howto build a CA Server?

**Comment by briansmith** [comment]
This is being tracked in the "Proxy Privacy" GitHub project at https://github.com/runconduit/conduit/projects/1. (I'm not sure how well a GitHub project will work for tracking this, but I'll give it a shot.)

**Comment by briansmith** [comment]
I'm going to close this as it's not an actionable issue itself, as "secure" means many different things. The project https://github.com/runconduit/conduit/projects/1 tracks the TLS implementation.
