### ISSUE TITLE
Grafana "Outbound Deployments" count seems off

### ISSUE THREAD

**Issue by bourquep** [runconduit/conduit#801]
Looking at the Grafana dashboard for a deployment, it shows 216 outbound deployments:

<img width="208" alt="image" src="https://user-images.githubusercontent.com/65096/38968043-cb65270a-4357-11e8-9d1c-8e7fe16efb21.png">

However, this particular deployment only connects to 2 other services (deployments), totalling 18 pods.

So either the reported number is off, or what the number actually means is mislabeled. Is it the number of active outbound connections?

**Comment by siggy** [comment]
Thanks for the report @bourquep. This is unexpected. That stat is based on the following Prometheus query (templating via Grafana):
```
count(request_total{namespace="$namespace", deployment="$deployment", dst_deployment=~"$outbound", direction="outbound"})
```
I suspect this may be related to #705. In your deployment dashboard, browse to the Grafana Dashboard Settings in the upper-right, then click `Variables`. Browse through the four variables, note the `Preview of values` section at the bottom. If you see a variable with a lot of values, or an empty value, that's likely the culprit.

Also helpful in investigating these types of issues, connect directly to Prometheus to run queries:
```bash
$ kubectl -n conduit port-forward $(kubectl --namespace=conduit get po --selector=conduit.io/control-plane-component=prometheus -o jsonpath='{.items[*].metadata.name}') 9090:9090 &
$ open localhost:9090
```
