### ISSUE TITLE
CLI should read the env var: KUBECONFIG

### ISSUE THREAD

**Issue by fleeto** [runconduit/conduit#828]
Like others, get kubeconfig file location from it.

**Comment by briansmith** [comment]
Hi @fleeto, we should be honoring KUBECONFIG already. If not, we would appreciate details of what's going wrong when you tried it.

**Comment by fleeto** [comment]
@briansmith Thanks for your reply. There is a conduit cli v1.0 in my `/usr/local/bin`. So its my fault :).
