### ISSUE TITLE
[Getting Started] conduit stat deployments --namespace=emojivoto

### ISSUE THREAD

**Issue by DazWilkin** [runconduit/conduit#838]
The (otherwise excellent) "Getting Started" has (I think) a bug:

https://conduit.io/getting-started/#using-the-cli

`conduit stat deployments` (no longer) displays the `emojivoto` Deployments because these are under the `emojivoto' namespace.
```
conduit stat deployments
No traffic found.
```
Recommend:
Changing the instruction to `conduit stat deployments --namespace=emojivoto` which WAI

```
conduit stat deployments --namespace=emojivoto
NAME       MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
emoji         1/1   100.00%   2.0rps           1ms           1ms           1ms
vote-bot      1/1         -        -             -             -             -
voting        1/1    88.33%   1.0rps           1ms           1ms           2ms
web           1/1    94.02%   1.9rps           2ms           4ms           5ms
```

**Comment by siggy** [comment]
Thanks for filing @DazWilkin. I was literally making that doc change as this issue came in. Stay tuned for PR!
