### ISSUE TITLE
Grafana: Conduit Health dashboard can show metrics from deployments in other namespaces

### ISSUE THREAD

**Issue by hawkw** [runconduit/conduit#852]
The Conduit Health Grafana dashboard can sometimes display metrics from deployments in (non-control-plane) namespaces whose names are the same as that of a Conduit control plane deployment. 

For example, when Emojivoto is deployed with Conduit, it creates a deployment in the `emojivoto` namespace called `web`. The Conduit dashboard also creates a deployment in the `conduit` namespace called `web`. The Conduit Health dashboard looks like this:
![screen shot 2018-04-25 at 3 13 38 pm](https://user-images.githubusercontent.com/2796466/39276511-2521abc4-489e-11e8-8115-c579a07b9cfd.png)

Notice how the `web` deployment's charts show twice as many lines as the other deployments (2 for success rate and request rate, 6 for latency percentiles). This is because these charts are also incorrectly including the metrics for the `emojivoto/web` deployment.

/cc @siggy

**Comment by siggy** [comment]
Relates to #823.
