### ISSUE TITLE
Reuse `ResolverFuture` instead of cloning a new one for each lookup

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#859]
A `ResolverFuture` is very heavyweight and we should avoid constructing a new one each time we do a DNS lookup. I have a PR to improve this, but it is blocked on https://github.com/bluejekyll/trust-dns/issues/430.

**Comment by hawkw** [comment]
Now that bluejekyll/trust-dns#487 has landed, I'm planning on changing Conduit's DNS module to use the new API added in that PR. This should have the side benefit of fixing this issue as well.
