### ISSUE TITLE
Add flag to set proxy bind timeout environment variable

### ISSUE THREAD

**Issue by sfroment** [runconduit/conduit#863]
Hello,

I have some request that need time to complete, so I was wondering if we could add a proxy-bind-timeout flag on conduit inject? I've already done my own change https://github.com/sfroment/conduit/commit/cf33ee96c88f70e78154f7ded88945ee2925e080

**Comment by siggy** [comment]
@sfroment Thanks for filing (and for the diff)! I think this is a good feature to add. I've tested this locally and it works. Would you mind creating a PR?

**Comment by seanmonstar** [comment]
I know there's been some discussion about how we should handle timeouts, and I feel like some of that has been that we may want to remove the bind timeout we have currently, and replace it with something more complete. @olix0r and @briansmith spoke the most about it, if I remember correctly.

**Comment by sfroment** [comment]
@siggy #865 
@seanmonstar Say me if I need to close are made change :)

**Comment by briansmith** [comment]
I don't object to creating the flag to `conduit inject` until we have the timeout situation sorted out. I do think we need to get rid of this timeout but we'd need a plan that would require non-trivial effort to write up and implement.

**Comment by klingerf** [comment]
This was fixed in #865. Thanks @sfroment!
