### ISSUE TITLE
Conduit should configure tokio-timer in a way that avoids creating new threads just for the timer

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#867]
The DNS dependency, Trust-DNS, released a version (0.8.2) basically just for us that, amongst other things, avoids using the new tokio's tokio-timer. However, we need to upgrade to the 0.9 (master branch) series to get new bug fixes. The master branch there uses tokio_timer::Delay and tokio_timer::Deadline. My understanding is that we have to do something explicit to configure tokio-timer to get it to work without creating its own background threads but I don't know how to do so.

@carllerche What do we need to do?

**Comment by carllerche** [comment]
Either update to the latest tokio-core (which uses the new timer under the hood) or configure it to run manually. This would pull in the new reactor and thread pool as well though.

A helpful guide on how to "build a runtime": https://tokio.rs/docs/going-deeper/building-runtime/

The idea would be that you would wrap `core.run` w/ `timer::with_default`.

**Comment by hawkw** [comment]
As of 82e6f717cf56edfb554dc9eb4853845c2afe4fa9, I can confirm that my Tokio upgrade branch (#944) only creates two threads, just like the current master:
```
➜ RUST_BACKTRACE=1 CONDUIT_PROXY_POD_NAMESPACE=fake CONDUIT_PROXY_CONTROL_URL=tcp://lol.cluster.whatever.local:666 CONDUIT_PROXY_LOG=info,conduit_proxy=debug CONDUIT_PROXY_PRIVATE_FORWARD=tcp://127.0.0.1:9999 cargo run -p conduit-proxy
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/conduit-proxy`
DBUG conduit_proxy::task creating single-threaded proxy
INFO conduit_proxy using controller at HostAndPort { host: DnsName(Name("lol.cluster.whatever.local")), port: 666 }
INFO conduit_proxy routing on V4(127.0.0.1:4140)
INFO conduit_proxy proxying on V4(0.0.0.0:4143) to Some(Addr(V4(127.0.0.1:9999)))
INFO conduit_proxy serving Prometheus metrics on V4(127.0.0.1:4191)
INFO conduit_proxy protocol detection disabled for inbound ports {25, 3306}
INFO conduit_proxy protocol detection disabled for outbound ports {25, 3306}
ERR! conduit_proxy::control "controller-client", controller error: Error attempting to establish underlying session layer: DNS resolution failed
^X^Z
[1]  + 50520 suspended  RUST_BACKTRACE=1 CONDUIT_PROXY_POD_NAMESPACE=fake CONDUIT_PROXY_CONTROL_URL=

✦ ➜ ps -M 50520
USER    PID   TT   %CPU STAT PRI     STIME     UTIME COMMAND
eliza 50520 s002    0.0 S    31T   0:00.01   0:00.14 target/debug/conduit-proxy
      50520         0.0 S    31T   0:00.01   0:00.26
```
