### ISSUE TITLE
(Feature request) Support for injection in StatefulSets

### ISSUE THREAD

**Issue by oivindoh** [runconduit/conduit#907]
I've currently migrated some redis instances I previously had in the servicemesh from the ill-advised use of deployments previously to statefulsets with stable storage now.

Thus, these services are not part of the conduit mesh because the deployment object type isn't one of the supported types (I tried cheating by just reusing the injection I had in my previous deployments, but upon having a peek in the repo this seems to not be supported at all.

Here's a formal wishlist entry for StatefulSet to be awarded full conduit citizenship 🥇

**Comment by grampelberg** [comment]
@oivindoh see #910

**Comment by oivindoh** [comment]
Nice! Looking briefly over the repo I don’t really understand whether there’s any additional plumbing that must be done on the proxy side to get these sets into the mesh proper?
