### ISSUE TITLE
Change API URLs to avoid triggering ad blockers

### ISSUE THREAD

**Issue by klingerf** [runconduit/conduit#970]
As we discovered in #896, some adblocker configurations can block XHR requests made by the Conduit web UI, causing the UI to not work as expected. We should investigate how hard it would be to add adblocker detection and warn the user that the dashboard won't work with adblockers enabled.

**Comment by briansmith** [comment]
It seems likely to me there is a way to avoid the ad blockers breaking things. It seems likely we're doing something that seems like something an ad would do, that a normal (React) app that uses XHR wouldn't do. Do we know why exactly the ad blockers block XHR requests made by the Conduit web UI? Which ad blocking rule are we triggering? Can we change our XHRs to avoid trigger that ad blocking rule? Can we submit a tweaked version of the ad blocking rule upstream?

**Comment by hawkw** [comment]
@briansmith I believe that one of our XHR requests has a path that includes `/api/stat`, which apparently triggers a blocking rule in uBlock Origin. See https://github.com/runconduit/conduit/issues/896#issuecomment-390124997.

**Comment by olix0r** [comment]
The rule comes from the [EasyPrivacy](https://forums.lanik.us/) list, which forbids:

```
/api/0/stats
/api/analytics/*
/api/log?
/api/lt/ref?
/api/pageview?
/api/pixel?
/api/stat?
/api/tracking/*
/api/v1/stat?
/api/x.gif?
```

**Comment by briansmith** [comment]
> @briansmith I believe that one of our XHR requests has a path that includes /api/stat, which apparently triggers a blocking rule in uBlock Origin. See #896 (comment).

Thanks I see "/api/stat?" in this blocklist: https://easylist.to/easylist/easyprivacy.txt. It seems like all we have to do is change that URL and everything will work. That seems much better than letting the ad blocker block the XHR and then reporting on it.

**Comment by grampelberg** [comment]
Some URL proposals (all of these pass the easylist at least):

```
/api/control-plane/stat
/api/details
/api/traffic
/control-plane/stat
/backend/stat
/api/v2/stat
```

My vote is `/api/v2/stat`. `/api` feels like a good base and I like keeping the routes the same as the CLI commands they're mirroring.

**Comment by olix0r** [comment]
Given that `/api/v1/stat?` is in the blocklist, I would lean towards using another non-versioned namespace (since this isn't really a versioned api anyway, is it?).  Given that the protobuf api is in the `conduit.public` namespace, perhaps `/api/public/stat`?

**Comment by briansmith** [comment]
I suggest we try to think of something more creative (unique) than "stat" to use in the URL. Any generic URL similar to the ones we've mentioned so far seem very likely to be put into add blocker blacklists in the future. I suggest "/api/v1/tps-reports".

Regarding whether or not the API is versioned: As we get closer to the 1.0 release I think we need to make sure all APIs are versioned one way or another. Whether that happens in the URL I don't know.

**Comment by grampelberg** [comment]
@briansmith any suggestions for a better named `stat` endpoint?

**Comment by grampelberg** [comment]
Current winner: `/api/tps-report`
