### ISSUE TITLE
Web: add coverage reporting to tests

### ISSUE THREAD

**Issue by grampelberg** [runconduit/conduit#999]
It wouldn't be particularly hard to add coverage to the tests. What does everyone think?

**Comment by grampelberg** [comment]
@klingerf @rmars ^^ ?

**Comment by klingerf** [comment]
I don't feel too strongly about test coverage, but it probably doesn't hurt. In repos that I've previously worked in, test coverage reports went mostly ignored unless developers were forced to pay attention to them, either by way of CI or email or some other setup. If we're going to add coverage reports, we should put them somewhere that people will see them.

**Comment by grampelberg** [comment]
I'm not sure what my opinion is on it either. In the past, it has helped me hunt down bugs missed by tests (usually logic branches that I wasn't actually using/testing). That said, it can also be a pretty big burden without any huge gains. Given that it slows the tests down (3s -> 5s), I'm inclined to say that we suggest it as a tool to check that new tests are going through all the logic branches and just leave it at that.

If we *did* decide that it was a good idea, it'd need to be part of normal test running and a check for CI to pass the build. Otherwise, to your point @klingerf it is just data that isn't worth it.

**Comment by rmars** [comment]
Yeah, I don't have strong feelings about this either. It is a nice to have; if it slows the tests down a lot, then maybe just as a suggested tool.

**Comment by grampelberg** [comment]
Sounds like it is a "not for now". We can revisit later if it makes sense then =)
